### ISSUE TITLE
Issue with syncing JDS mempool full transaction.

### ISSUE THREAD

**Issue by Shourya742** [stratum-mining/stratum#1005]
The JDC declares a DMJ to the JDS. If the JDS does not have some transactions from the tx_hash_list, it sends back a PMT with the missing transaction IDs. The JDC then sends the full transactions corresponding to these missing IDs.

However, there's an unexpected issue. Ideally, the JDS should have already populated all known transactions into the mempool using add_tx_data_to_mempool. But as indicated in the screenshot, there are several transactions whose full data is still unknown to the mempool. This should not occur, since we are supposed to populate the full transaction list through add_data_tx_to_mempool even before sending the PMT

Sequence diagram:

JDC      ---> JDS : Declare DMJ
JDS      ---> JDC : Send PMT with missing transaction IDs (if any)
JDC      ---> JDS : Send full transactions for missing IDs
JDS      ---> Mempool : Add transactions using `add_tx_data_to_mempool`
JDS      ---> Identify Issue : Full data for several transactions is still unknown to the mempool

There are two potential solutions:
1. Investigate any omissions in the `add_tx_data_to_mempool` process.
2. Add the transactions with missing data to `missing_tx`, which will then retrieve the transaction data via PMTS.

**Comment by plebhash** [comment]
hey @Shourya742 thanks for reporting this

are you able to reproduce this issue as a MG test?

**Comment by Shourya742** [comment]
> hey @Shourya742 thanks for reporting this
> 
> are you able to reproduce this issue as a MG test?

I am not sure if we can reproduce this via the MG test, as we are not yet logging such discrepancies. This can be caught once we have the todos in place in the JDS module.

**Comment by Shourya742** [comment]
Closing this issue as it is related to: https://github.com/stratum-mining/stratum/issues/840 and is currently being addressed via this PR: https://github.com/stratum-mining/stratum/pull/868
