### ISSUE TITLE
Consider changing the default branch to reflect the current git flow

### ISSUE THREAD

**Issue by jbesraa** [stratum-mining/stratum#1031]
Currently we merge to `dev` branch and in practice use it as the default branch, while `main` is reserved as a release branch. This setup makes it necessary to update each PR opened against `dev` on each change in `dev` even if not conflicting with the opened PR. I suggest we set `dev` as default branch in github settings to avoid that.

As a side note, I am not a big fan of `dev` + `main` workflow but  thats a different discussion. While we have this setup already, lets make it as good as possible. 

@Fi3 would appreciate your input as it seems you have admin access to the repo

**Comment by Shourya742** [comment]
I agree with this. Setting the `dev` branch as the default for all immediate merges makes sense, while reserving the `main` branch for releases. This is the workflow I've observed in most organizations. It makes sense and prevents an endless cycle of rebasing.

**Comment by Fi3** [comment]
Make sense, I don't remember why is not dev the base branch. I also would like to know why you don't like this workflow, and possible alternatives.

**Comment by jbesraa** [comment]
@Fi3 did you get the chance to change `dev` to default branch?
in regards to your question:
1- having `dev` branch gives the notion that this is not production, while it is..
2- having a separate release branch can be in a separate dedicated branch(`release`?)  with its own specific configuration(linear history and so on) (iam not a big fan of release branches in general, imo we should relay on releasing through github and having tagged branches, but iam not exactly sure how our release process looks like now)
3- all the info github providing about the repo activity are stall between releases(see this https://github.com/stratum-mining/stratum/graphs/commit-activity, it looks as no commits since june), maybe this can be solved when setting `dev` to default branch.. not sure
4- most of bitcoin os projects are using `main/master` and its set to default branch in the repo, it would be nice to follow that

**Comment by Fi3** [comment]
This is mostly naming issues and I'm not really interested everything will work. What I'm interested in is:

> iam not a big fan of release branches in general, imo we should relay on releasing through github and having tagged branche

Can you elaborate that point please? Ty
