### ISSUE TITLE
JDS is missing checks on DeclaredMiningJobs

### ISSUE THREAD

**Issue by GitGab19** [stratum-mining/stratum#1054]
While discussing with @plebhash about #1053, I saw that our current JDS is not checking DeclaredMiningJobs. And more specifically, there's still a TODO in the message handlers: https://github.com/stratum-mining/stratum/blob/7841021e3f20280c62af119de5de58f421c6e428/roles/jd-server/src/lib/job_declarator/message_handler.rs#L32-L36

We should address that TODO, implementing the checks mentioned there.

**Comment by plebhash** [comment]
closing, this is a duplicate of https://github.com/stratum-mining/stratum/issues/986
