### ISSUE TITLE
Define `systemd` example for roles

### ISSUE THREAD

**Issue by marathon-gary** [stratum-mining/stratum#1057]
Define an example in README for running roles via `systemd` and other common daemon handlers

**Comment by plebhash** [comment]
I don't think SRI should be catering for these kind of use-cases.

If someone wants to deploy SRI roles via `systemd` or some other opinionated way, that could be done in a separate repository.

Bringing this over here implies that SRI contributors will have to allocate bandwidth towards reviewing and maintaining this.

**Comment by Sjors** [comment]
Whether here or elsewhere, it would be useful to have this info.
