### ISSUE TITLE
Long submission time

### ISSUE THREAD

**Issue by fsj-p** [stratum-mining/stratum#1061]
The difficulty of node setup is relatively low, but the average time to mine a new block is long

**Comment by pavlenex** [comment]
Hey @fsj-p can you please provide more details and logs, we cannot do anything with information you've provided. You need to post a detailed log, explain your setup and configs and post logs of every part of the stack, otherwise this issue doesn't mean much, same goes for #1062 and #1063

**Comment by fsj-p** [comment]
Set the template difficulty to 1 in tbc.
Start the tbc program with only the "-connect=0" parameter.
Invalidate nodes with high difficulty using the invalidateblock interface.
Close the node.
Start the node with "-connect=0", "-standalone" and sv2 related parameters.
Use config A to complete the connection.
Observe the time print of updateTip in btc, the time interval is very long.
[bitcoind.log](https://github.com/user-attachments/files/16309224/bitcoind.log)
[pool.log](https://github.com/user-attachments/files/16309235/pool.log)

**Comment by fsj-p** [comment]
[jds_upper_part.log](https://github.com/user-attachments/files/16309387/jds_upper_part.log)
[jds_middle_part.log](https://github.com/user-attachments/files/16309388/jds_middle_part.log)
[jds_lower_part.log](https://github.com/user-attachments/files/16309392/jds_lower_part.log)

**Comment by GitGab19** [comment]
> The difficulty of node setup is relatively low, but the average time to mine a new block is long

Are you using testnet4?
If so, it's very unlikely you are going to mine a block using cpu-miner
