### ISSUE TITLE
cpuminer will be disconnected

### ISSUE THREAD

**Issue by fsj-p** [stratum-mining/stratum#1063]
Using configa, it was found that cpuminer would be disconnected after mining for a period of time, and then it would keep disconnecting and reconnecting.

**Comment by fsj-p** [comment]
The node difficulty is set very low. Use configuration A to connect BTC, SRI, and cpuminer.
Begin mining. cpuminer may continue to disconnect and reconnect.
[bitcoind.log](https://github.com/user-attachments/files/16308930/bitcoind.log)
[jdc.log](https://github.com/user-attachments/files/16308931/jdc.log)
[jds.log](https://github.com/user-attachments/files/16308932/jds.log)
[miner.log](https://github.com/user-attachments/files/16308933/miner.log)
[pool.log](https://github.com/user-attachments/files/16308934/pool.log)
[proxy.log](https://github.com/user-attachments/files/16308935/proxy.log)

**Comment by GitGab19** [comment]
Could you please provide some smaller and more specific logs?
If something is wrong, you should see some errors or panics somewhere (probably on JDC logs, or Translator logs)
