### ISSUE TITLE
remove `JobDistributionProtocol` from `common_messages_sv2 `

### ISSUE THREAD

**Issue by plebhash** [stratum-mining/stratum#1065]
during the [review process](https://github.com/stratum-mining/stratum/pull/1035/files#r1677822834) of #1035 we identified that `common_messages_sv2` crate has some references to `JobDistributionProtocol`, which is just some legacy terminology that we forgot to remove after some spec changes

if we check [stratumprotocol.org/specification](https://stratumprotocol.org/specification/) we'll only find 3 subprotocols:

- Mining
- Job Declaration
- Template Distribution

but the `Protocol` enum declaration includes 4 different subprotocols:
https://github.com/stratum-mining/stratum/blob/7841021e3f20280c62af119de5de58f421c6e428/protocols/v2/subprotocols/common-messages/src/setup_connection.rs#L293-L298

all references to `JobDistributionProtocol` should be cleaned up

**Comment by Shourya742** [comment]
@plebhash, can I take this on? This will help me understand the APIs in the protocol, which might be useful during future refactoring.
