### ISSUE TITLE
Proxy does not perform check_target

### ISSUE THREAD

**Issue by fsj-p** [stratum-mining/stratum#1067]
Set the template difficulty to 0x1d07ffff in tbc.
Start the tbc program with only the "-connect=0" parameter.
Invalidate nodes with high difficulty using the invalidateblock interface.
Close the node.
Start the node with "-connect=0", "-standalone" and sv2 related parameters.
Use config A to complete the connection.
Observe the time print of updateTip in btc, the time interval is very long.
[miner.log](https://github.com/user-attachments/files/16309797/miner.log)
[proxy.log](https://github.com/user-attachments/files/16309798/proxy.log)

**Comment by GitGab19** [comment]
Are you using testnet4 or testnet3?
Why do you need to set a custom template difficulty?
