### ISSUE TITLE
 Add fmt an clippy as git hook for commit

### ISSUE THREAD

**Issue by Fi3** [stratum-mining/stratum#1073]
Before committing is very useful to always have fmt and clippy executed so we avoid to have the git log full of fmt and clippy and git blame is more likely to point to the right commit.

**Comment by xyephy** [comment]
@Fi3 Should I place the `pre-commit` file under the `.githooks` directory?

**Comment by xyephy** [comment]
> @Fi3 Should I place the `pre-commit` file under the `.githooks` directory?

I'm also getting some errors related to #1048

**Comment by Shourya742** [comment]
Hey @xyephy, there’s already an ongoing PR for this issue: https://github.com/stratum-mining/stratum/pull/1039

**Comment by xyephy** [comment]
> Hey @xyephy, there’s already an ongoing PR for this issue: #1039

Thanks for the heads up @Shourya742 , will have a look at it.

**Comment by GitGab19** [comment]
Closing this as addressed by #1039

**Comment by GitGab19** [comment]
Closing this as addressed by https://github.com/stratum-mining/stratum/pull/1039
