### ISSUE TITLE
Optimise contributing and release processes

### ISSUE THREAD

**Issue by jbesraa** [stratum-mining/stratum#1098]
Conversation moved from #978 to this issue.

## Items to Include
- [x] Consider using release branches and use a single main branch - for example for release `1.0.3` we can maintain only `main` branch and when we are ready for release we create a new branch/tag `1.0.3` and release to it

**Comment by plebhash** [comment]
ideally this issue should be solved by proposing a PR that establishes the new conventions under:
- [`CONTRIBUTING.md`](https://github.com/stratum-mining/stratum/blob/dev/CONTRIBUTING.md)
- [`README-DEV.md`](https://github.com/stratum-mining/stratum/blob/dev/README-DEV.md)
- [`RELEASE.md`](https://github.com/stratum-mining/stratum/blob/dev/RELEASE.md)

**Comment by jbesraa** [comment]
Suggestions from @rrybarczyk 

- [ ] Enforce each PR should have a branch associated with it and linked in GitHub's "Development" section on the Issue/PR.
- [ ] Enforce branch naming `yyyy-mm-branch-name`.
  - [ ] Branch names must start with the year (`yyyy`) and month (`mm`).
  - [ ] Words in branch names must be separated by a `-`.
  - [ ] Branch names must be short but descriptive and in present tense. It should contain the action/what is being added/fixed.
- [ ] Issue names should be the "problem" (as opposed to the solution). For example, "Bug in message generator `SubmitShare` `channel_id` test" or "Translator proxy config fails to parse downstream IP address".
- [ ] Pull request names should be the "solution" (as opposed to the problem). For example, "Increment message generator `SubmitShare` `channel_id` field value" or "Translator parse downstream IP as socket addr immediately on read".

**Comment by jbesraa** [comment]
I would suggest to separate the contrib/release process. I am not very much in favor of changing the current contrib process as I think adding https://github.com/stratum-mining/stratum/pull/991 is enough. its more a matter of enforcing it.

In general iam not a big fan of enforcing branch/issue/pr titles. I try to always read the issue body and if there is a pull request then its commits titles and content.

**Comment by plebhash** [comment]
I think the only change to `CONTRIBUTING.md` would be the references we have to `dev` branch there.

**Comment by jbesraa** [comment]
We should combine `CONTRIBUTING` and `README-DEV`. This is the first time I see `README-DEV` actually exist..

**Comment by plebhash** [comment]
> We should combine `CONTRIBUTING` and `README-DEV`. This is the first time I see `README-DEV` actually exist..

that sounds good to me
