### ISSUE TITLE
Rust Docs + refactor: `roles` crates

### ISSUE THREAD

**Issue by rrybarczyk** [stratum-mining/stratum#1117]
# Background
Currently, the `protocols` and `roles` crates are not production ready and contain code debt that needs to be addressed. This effort is discussed in #1069. The `protocols` tracker issue is in #845. This issue's purpose is the same as #845, only is directed at the `roles` crates.

The high-level process will be (see [this comment in discussion 1069](https://github.com/stratum-mining/stratum/discussions/1069#discussioncomment-10290635) for a more detailed plan of action)
1. Complete `protocols` Rust docs and identify any code debt (including `panic`s, `todo`s, and `unimplemented`s). Note that the `protocols` crates are fairly set and major architecture changes are not anticipated.
2. Complete `roles` Rust docs and identify code debt. Note that these crates will likely have notable architecture changes.
3. Implement `protocols` changes.
4. Implement `roles` changes.

Along side of this effort is #270 (and perhaps others, @plebhash?), which aims to address critical message generator issues. This initial message generator work would be to fix the critical issues, but these changes should/will be made mindfully as to introduce as little change as possible to not interfere with the overall/long term protocols and roles refactor effort.

# Task List

## Refactor Implementation
- [ ] #1093
- [ ] TODO

**Comment by plebhash** [comment]
adding a new label `needs-more-planning` here to explicitly state that this is not actionable yet

#845 should be prioritized over this

**Comment by rrybarczyk** [comment]
Let's keep track of all of these issues in #1069 in [this comment](https://github.com/stratum-mining/stratum/discussions/1069#discussioncomment-10397507).

This choice is made because the `roles` refactor involves architecture changes and some of the `roles` issues may actually not be needed after that architecture is set, so an issue to track them may be premature, but the discussion is a good spot.

**Comment by Fi3** [comment]
protocols IMO are prod ready. Are very well tested and they work well, there aren't any perf issues that I'm aware of. The only thing that is needed it better documentation.
