### ISSUE TITLE
Migrate Sv2 Roles to use rust-bitcoincore-rpc

### ISSUE THREAD

**Issue by marathon-gary** [stratum-mining/stratum#1123]
https://github.com/rust-bitcoin/rust-bitcoincore-rpc

https://github.com/stratum-mining/stratum/pull/1095#issuecomment-2297535225
https://github.com/stratum-mining/stratum/pull/1095#pullrequestreview-2238297569

There's probably a checklist to be made here for follow on issues/PRs.

**Comment by Fi3** [comment]
we removed that dependency why do you want re add it? @lorbax

**Comment by jbesraa** [comment]
> we removed that dependency why do you want re add it? @lorbax

why was it removed?

@marathon-gary do you mind please explaining why you would prefer `rust-bitcoincore-rpc` over `mini-rpc` ?

**Comment by marathon-gary** [comment]
> we removed that dependency why do you want re add it?

I was unaware of this history, I'll dig through issues/PRs to find the reasoning.

> do you mind please explaining why you would prefer rust-bitcoincore-rpc over mini-rpc ?

Reducing the amount of code that needs to be maintained is the first thing that comes to mind. 
Aside from that, I don't have a technical argument, as I assume `mini-rpc` works fine.

**Comment by marathon-gary** [comment]
https://github.com/stratum-mining/stratum/pull/761#issuecomment-1953757370
Found this reasoning but didn't dig into what the import problem is. Would be fine to leave as is since it works.

**Comment by Fi3** [comment]
if I remeber correctly was to have somthing with an async api but not sure maybe @lorbax remeber better.
Btw  that remove a dependecy that per se is not bad

**Comment by lorbax** [comment]
json-rpc uses serde for serializing and deserializing. The way it is imported is non compatible with the way it is imported in the libraries. To fix this error requires likely much more work than writing it ex novo.

**Comment by jbesraa** [comment]
Is there a documentation of the actual error?

**Comment by lorbax** [comment]
> Is there a documentation of the actual error?

no, but it is easy to try, you have to use bitcoincore-rpc and as I remember you get an error by just importing it.
