### ISSUE TITLE
Consider moving to a single workspace

### ISSUE THREAD

**Issue by jbesraa** [stratum-mining/stratum#1125]
Currently `roles` and `protocols` are separated and we have two workspaces in addition to `common` and other utils packages scattered around in the root folder. After we have completed https://github.com/stratum-mining/stratum/pull/994 I suggest to do the next step, combining the protocols/roles/common into a single workspace and rename each one to have a `stratum` prefix, i.e., `stratum-protocols` and so on.

**Comment by Fi3** [comment]
My undestanding was that we were ok in put roles and protocols in different git repos (we disscussed it in a call if I remeber correctly) why now you want to put them in the same workspace? Common can fo with protocols I guess
