### ISSUE TITLE
stop publishing `roles` to `crates.io`

### ISSUE THREAD

**Issue by plebhash** [stratum-mining/stratum#1128]
our `release-libs` workflow is publishing all `roles` crates to `crates.io`

those crates are merely PoCs and not nearly close to production readiness, and won't be for a while

for now, we could simply stop publishing them

https://github.com/stratum-mining/stratum/blob/0f0ee1e32a7cdeb9af83718364e0896b36744824/.github/workflows/release-libs.yaml#L142-L166

**Comment by plebhash** [comment]
tbh I'm leaning towards only publishing the crates under `protocols`, and not publishing anything else.

@Fi3 should we keep publishing any of these?
- `network_helpers_sv2`
- `rpc_sv2`
- `bip32-key-derivation`
- `error-handling`
- `key-utils`

**Comment by Fi3** [comment]
> tbh I'm leaning towards only publishing the crates under `protocols`, and not publishing anything else.
> 
> @Fi3 should we keep publishing any of these?
> 
>     * `network_helpers_sv2`
> 
>     * `rpc_sv2`
> 
>     * `bip32-key-derivation`
> 
>     * `error-handling`
> 
>     * `key-utils`

yes we should keep publishing them they are fundamental for implementing a role, why do you want stop publishing them?
