### ISSUE TITLE
https://stratumprotocol.org/specification/06-Job-Declaration-Protocol/#617-identifytransactions-server-client

### ISSUE THREAD

**Issue by CietyGoblin** [stratum-mining/stratum#1137]
https://stratumprotocol.org/specification/06-Job-Declaration-Protocol/#617-identifytransactions-server-client
> Sent by the Server in response to a DeclareMiningJob message indicating it detected a collision in the `tx_short_hash_list`, or was unable to reconstruct the `tx_hash_list_hash`.

The client receives an IdentifyTransactions message from the server, indicating a collision or inability to reconstruct the hash list of tx's. Currently, there is [just an empty vec returned.](https://github.com/stratum-mining/stratum/blob/dev/roles/jd-client/src/lib/job_declarator/message_handler.rs#L45) 

According to spec it should be providing:
> The full list of transaction data hashes used to build the mining job in the corresponding DeclareMiningJob message

The original `DeclareMiningJob` only contains `tx_short_hash_list` and `tx_hash_list_hash`. An `IdentifyTransactions` message indicates there was a collision in the `short hash` list or the `hash list hash` couldn't be recreated.

I assume the client just looks up the original list of tx's and then sends it back in the `.Success` message.

I will take a pass at a PR for this

_Originally posted by @marathon-gary in https://github.com/stratum-mining/stratum/issues/902#issuecomment-2214808996_

**Comment by GitGab19** [comment]
What's the reason behind opening this new issue?
It's already logged in #902

**Comment by pavlenex** [comment]
It's a spam.
