### ISSUE TITLE
framing_sv2 set wrong header channel bit 

### ISSUE THREAD

**Issue by Fi3** [stratum-mining/stratum#1147]
This function in framing_sv2::framing:

```rust
fn update_extension_type(extension_type: u16, channel_msg: bool) -> u16 {
    if channel_msg {
        let mask = 0b1000_0000_0000_0000;
        extension_type | mask
    } else {
        let mask = 0b0111_1111_1111_1111;
        extension_type & mask
    }
}
```

Set the bit 0 as channel bit. But spec say that have to be bit 15, 0-indexed,  https://github.com/stratum-mining/sv2-spec/blob/main/03-Protocol-Overview.md#32-framing.

The below function should fix the issue
```rust
fn update_extension_type(extension_type: u16, channel_msg: bool) -> u16 {
    if channel_msg {
        let mask = 0b0000_0000_0000_0001;
        extension_type | mask
    } else {
        let mask = 0b1111_1111_1111_1110;
        extension_type & mask
    }
}
```

**Comment by xyephy** [comment]
Hi @Fi3  can I give this a try?

**Comment by Fi3** [comment]
sure @xyephy

**Comment by plebhash** [comment]
@xyephy please work on top of this https://github.com/stratum-mining/stratum/pull/1049

**Comment by xyephy** [comment]
> @xyephy please work on top of this #1049

Noted.

**Comment by jakubtrnka** [comment]
In my opinion. the channel-bit should be the **most significant** bit in the extension_type field.
That means in the serialized form it should be the 15'th bit counted from zero. It's because we use little-endian representation.

This means, I probably disagree with the proposed change.

**Comment by Fi3** [comment]
@jakubtrnka is right we can close this issue 0b1000_0000_0000_0000 already set the most significant bit. @xyephy
