### ISSUE TITLE
Need Rust docs for `utils::buffer`

### ISSUE THREAD

**Issue by rrybarczyk** [stratum-mining/stratum#1184]
While doing the #1160 issue documenting the `codec-sv2` crate and realized there are several core primitives that are dependent on primitives in the `utils::buffer`. This crate should be properly documented.

Unrelated to this issue, we may want to consider in the future bringing `utils::buffer` into the `protocols/` directory.

**Comment by plebhash** [comment]
https://github.com/stratum-mining/stratum/issues/1009 is also closely related to this
