### ISSUE TITLE
need to bump crates versions for docs on release v1.1.0

### ISSUE THREAD

**Issue by plebhash** [stratum-mining/stratum#1221]
when we released `v1.1.0`, we did not bump versioning for the crates that received new Rust Docs:
- `codec_sv2`
- `const_sv2`
- `noise_sv2`

as a result, `cargo publish` failed during execution of `release-libs.yaml`.

for example, `const_sv2`:
```
Uploading const_sv2 v2.0.0 (/home/runner/work/stratum/stratum/protocols/v2/const-sv2)
error: failed to publish to registry at https://crates.io/

Caused by:
  the remote server responded with an error (status [40](https://github.com/stratum-mining/stratum/actions/runs/11365172913/job/31612774173#step:12:41)0 Bad Request): crate version `2.0.0` is already uploaded
```

this should be fixed by:
- bumping the MINOR version for these crates on the `v1.1.0` branch
- merging that back into `main`
- updating `v1.1.0` tag

**Comment by plebhash** [comment]
I'm already working on this

**Comment by jbesraa** [comment]
Why do you think it is related to the docs? I see here https://github.com/stratum-mining/stratum/actions/runs/11365172913/job/31612774173#step:15:70 all crates are not published. It is saying because the version number is already used.

**Comment by plebhash** [comment]
> https://github.com/stratum-mining/stratum/actions/runs/11365172913/job/31612774173#step:15:70

this is from a recent run, because I pushed the new tag
