### ISSUE TITLE
Clarification about template provider

### ISSUE THREAD

**Issue by Arshia-r-m** [stratum-mining/stratum#1261]
On Getting Started - Running all roles, it has been mentioned that after downloading proper release, the bitocin.conf must be edited.
There is already one bitcoin.conf file in the downloaded release which might cause confusion since the template provider reads the data of bitcoin.conf stored in ~/.bitcoin/, so it requires clarification .

**Comment by plebhash** [comment]
thanks for reporting this

issues on this repo are mainly focused for driving development of SRI

like you are already doing, this is something to be fixed on https://github.com/stratum-mining/stratumprotocol.org
