### ISSUE TITLE
Crates were not bumped in PR #1230

### ISSUE THREAD

**Issue by GitGab19** [stratum-mining/stratum#1275]
PR #1230 changed some crates under `protocols` to be `no_std`, without bumping their versions. 

Now this is creating some errors in the CI execution of `semver-checks`, such as here: https://github.com/stratum-mining/stratum/actions/runs/12211524808/job/34069218188?pr=1242.

We need to bump versions of crates which were modified there to fix this and unblock all the docs PRs.

Specifically, we need to bump the major version number of:
- `serde_sv2`
- `const_sv2`
- `framing_sv2`
- `buffer_sv2`

**Comment by jbesraa** [comment]
I would remove the GH from ci and move the checks into a script that we run manually before creating a new release

**Comment by plebhash** [comment]
> I would remove the semver check from ci and move it into a script that we run manually before creating a new release

@GitGab19 feels we should catch semver deviations as soon as possible

but it's also important to highlight that something is not working as expected

we merged #1230 without CI blocks, and now we are getting this behavior

ideally #1230 should have been blocked by this semver check

**Comment by plebhash** [comment]
> we merged https://github.com/stratum-mining/stratum/pull/1230 without CI blocks, and now we are getting this behavior
> 
> ideally https://github.com/stratum-mining/stratum/pull/1230 should have been blocked by this semver check

this happened because our CI was using whatever was the latest release of `cargo semver-checks`, and https://github.com/obi1kenobi/cargo-semver-checks/pull/1015 introduced a change of behavior into v0.37.0

the solution was https://github.com/stratum-mining/stratum/pull/1276 where we are locking CI to always use `cargo semver-checks` on release v0.33.0 in order to always have the same behavior of the tool

**Comment by plebhash** [comment]
todo: follow up to https://github.com/stratum-mining/stratum/pull/1276 that locks `cargo semver-checks` on 0.37.0

this CI will have to run on rust stable
