### ISSUE TITLE
need to migrate `sv1-mining-device` logs from `println! / eprintln!` to `tracing`

### ISSUE THREAD

**Issue by plebhash** [stratum-mining/stratum#1286]
[`sv1-mining-device`](https://github.com/stratum-mining/stratum/tree/main/roles/test-utils/mining-device-sv1) currently has a logging system based on `println!` and `eprintln!`

we should migrate this to `tracing`

use `mining-device` as a reference

**Comment by devworlds** [comment]
Hey @plebhash i uptade the printlns to info, but i cant't push a new branch to create pr, its my first make something to open-source, i need to so something before?

**Comment by plebhash** [comment]
closed via #1309
