### ISSUE TITLE
Rename free_encoder to flush_encoder

### ISSUE THREAD

**Issue by ccdle12** [stratum-mining/stratum#135]
While working on the template provider in C, the [free_encoder ffi](https://github.com/stratum-mining/stratum/blob/main/protocols/v2/sv2-ffi/src/lib.rs#L312) name is slightly confusing because my first thought was, this is used to free memory but its used to free up the encoder to allow the bytes in the buffer to be overwritten.

A better name imho would be `flush_encoder` as its more aligned with C/Linux APIs: https://linux.die.net/man/3/fflush.

**Comment by Eunoia1729** [comment]
So, we need 2 functions to be renamed :
1. `free_encoder` -> `flush_encoder`
2. `free_decoder` -> `flush_decoder`
 Am I right ?
 
The content in README will be modified too.

**Comment by ccdle12** [comment]
I'm not 100% sure on `free_decoder` at this stage, would suggest to ping  @Fi3. If `free_decoder` is the same behavior of `free_encoder`, then in that case I would be in favor of the update.

The README would need to be updated:   https://github.com/stratum-mining/stratum/blob/89020d660f41ffc83ffc66d97d5f6609a10269e8/examples/interop-cpp/README.md#encode-sv2-messages-in-c

The example C++ example using free_encoder: https://github.com/stratum-mining/stratum/blob/89020d660f41ffc83ffc66d97d5f6609a10269e8/examples/interop-cpp/template-provider/template-provider.cpp#L87

The sv2.h ffi header file would need to be regenerated with the updated free_encoder name: https://github.com/stratum-mining/stratum/blob/2a6fde447844188a9f1bb5e783eb9f125e1a44a7/protocols/v2/sv2-ffi/sv2.h

**Comment by Fi3** [comment]
Agree with using flush_encoder.
free_decoder can be removed.

**Comment by Fi3** [comment]
As @ccdle12 let me know now we are using free_decoder in the bitcoin core fork, so it can not be removed anymore
