### ISSUE TITLE
Add production branch

### ISSUE THREAD

**Issue by Fi3** [stratum-mining/stratum#169]
Add a branch called production where we merge main. The branch will be used to publish the libraries in crates.io. 
In the main branch in the Cargo.toml files we use relative paths cause it easier in a dev env, but in the production branch we should fetch dependency from crates.io

eg instead of:
```toml
codec_sv2 = { path = "../../../protocols/v2/codec-sv2", features=["noise_sv2"] }
```
do:
```toml
codec_sv2 = "x.y.z"
```

**Comment by rrybarczyk** [comment]
Related to  #58

**Comment by haru-02** [comment]
@Fi3  can i take up this issue ? to my understanding, we just have to make a new branch called production, and edit the version numbers in the Cargo.toml file, correct ?

**Comment by SumantxD** [comment]
@Fi3 can you assign me this issue, i would like to work on it

**Comment by Aankirz** [comment]
Hey @Fi3 ,

I've tried solving it here's the PR:

https://github.com/stratum-mining/stratum/pull/515

**Comment by Fi3** [comment]
No need it anymore we already have the bot/versioning branch
