### ISSUE TITLE
Pool + Template Provider: Both need to implement and handle CoinbaseOutputDataSize message

### ISSUE THREAD

**Issue by ccdle12** [stratum-mining/stratum#184]

**Comment by Fi3** [comment]
I think that this has very low priority. Maybe we can put it in a second core PR.

**Comment by ccdle12** [comment]
Still applicable, maybe MVP2

**Comment by rrybarczyk** [comment]
MVP1 works without this message, however should include in MVP1 for protocol completeness.

**Comment by pavlenex** [comment]
cc @ccdle12 Can we try to tackle this one to ensure completeness?

**Comment by ccdle12** [comment]
It's probably better suited to MVP2 considering MVP1 is pretty close I think. Adding new features late is probably not a great idea.

**Comment by pavlenex** [comment]
It seems this one is blocking @4ss0 and his progress on JN. Could we prioritize this?

**Comment by pavlenex** [comment]
Done in #393
