### ISSUE TITLE
C++: Template Provider needs to be able to flush cached blocks and block ids to disk in case of restart

### ISSUE THREAD

**Issue by ccdle12** [stratum-mining/stratum#185]

**Comment by ccdle12** [comment]
Informal chats with Matt indicated that the client should be caching and assuring durability. If the TP restarts, then the client can submit the candidate via Bitcoin RPC calls. But maybe we should consider adding a message to let the client know the id for the submitted solution doesn't exist so that the client can look for other means to get the block to the network.

**Comment by rrybarczyk** [comment]
@ccdle12 is this solved already?

**Comment by ccdle12** [comment]
After speaking briefly with Matt about this issue, he suggested the pool/client of the TP ensures durability.  I'm not sure how that work at this stage and there probably would need to be a new message to let a downstream client know that a template id is current not in memory of the TP.

So this issue probably needs further discussion.
