### ISSUE TITLE
Pool + Template Provider: Both need to handle RequestTransactionData message

### ISSUE THREAD

**Issue by ccdle12** [stratum-mining/stratum#186]

**Comment by Fi3** [comment]
I think that we could start the work on this when the JobNegotiatior part is more mature

**Comment by ccdle12** [comment]
Still applicable to C++ TP, but dependent on the work in the JN according to the above comment: https://github.com/stratum-mining/stratum/issues/186#issuecomment-1196433287

**Comment by Sjors** [comment]
Afaik this is done.
