### ISSUE TITLE
Template Provider: agree on minimum features for PR into Bitcoin Core

### ISSUE THREAD

**Issue by ccdle12** [stratum-mining/stratum#187]
Re-purposing this issue to compile a list of WIP issues that are potential candidates for a MVP/early concept ack for a Bitcoin PR for the Template Provider. Some of the following issues maybe removed if agreed they are not critical for the first iteration.

- [ ] #308 
- [x] #184 
- [x] #309
- [ ] #310
- [x] #311
- [x] #312
- [ ] #235 
- [ ] #314
- [ ] #185 - NOTE: I think we concluded the responsiblity of durability was on the Pool/direct downstream connection but the Pool will need to know if TP restarts and no longer contains the cached block, the Pool will need to find other means to submit the block to the p2p layer. (could be an additional message from the TP of block submission failure or something, or the TP does indeed need to flush cached blocks to disk).

**Comment by Fi3** [comment]
I think that:
1. on connection send out (1) newprevhash (2) template future=false (3) template future=true
2. on new block if not found by the pool send out (1) newprevhash (2) template future=false (3) template future=true
3. on new block if found by the pool send out (1) newprevhash template-id=previously sent future template (2) template future=false (3) template future=true
4. on submitsolution construct the block flush block cache and do (2)
5. coinbase tx is always completely chosen by the pool
6. we can add RequestTransactionData RequestTransactionData.Success in another PR or after that above part has been reviewed

**Comment by ccdle12** [comment]
> 1. on connection send out (1) newprevhash (2) template future=false (3) template future=true

Thanks for the feedback, to clarify - what does `(2) template future=false (3) template future=true` indicate?

**Comment by Fi3** [comment]
Send out 2 templates one with future=false with txs set that maximize block fee, other one with future=true with txs not included on first block. I thought on another point that should be in first PR I will update my above comment.

**Comment by ccdle12** [comment]
> Send out 2 templates one with future=false with txs set that maximize block fee, other one with future=true with txs not included on first block

Ok sounds good, this is an issue that captures that feature: https://github.com/stratum-mining/stratum/issues/189#issue-1319267521 feel free to edit to make it more accurate.

I guess the other thing is, the sequencing of sending the `SetNewPrevHash` for the second template which is set to future. I guess this would happen on the event of the best new block changing in the network e.g. receiving a best new block from the p2p layer or a downstream miner finding a solution?

**Comment by Fi3** [comment]
yep if downstream miner find a solution we can immediately start to mine a previously sent future template (point 3) if the block come from the network we need to send a newprevhash, a new newtemplate with future=false a new new template with future=true (point 2)

**Comment by ccdle12** [comment]
Still applicable to the C++ TP, but I think its probably a candidate for MVP2
