### ISSUE TITLE
Follow rust-lightnings custom logging pattern to support logging in roles crate

### ISSUE THREAD

**Issue by rrybarczyk** [stratum-mining/stratum#207]
- The `roles` binaries should have logging capabilities
- Rust lightning has created their own custom logging to gain logging functionality without using an external crate
- The rust-lightning logging logic is found [here](https://github.com/lightningdevkit/rust-lightning/blob/main/lightning/src/util/logger.rs) and [here](https://github.com/lightningdevkit/rust-lightning/blob/main/lightning/src/util/macro_logger.rs)
- Need to pull this logic in so it can be used in `roles`
- Need to verify it is non-blocking

**Comment by darricksee** [comment]
This was closed with https://github.com/stratum-mining/stratum/pull/303
