### ISSUE TITLE
Stratum V2 Feature Tracker / Roadmap candidate📋

### ISSUE THREAD

**Issue by pavlenex** [stratum-mining/stratum#221]
This issue can be used as a all in one place to post suggestions/ideas for new features, improvements to the SV2 that can be our roadmap candicated. The goal is to collect everything in one place, which we can use as a single source of truth, once deciding what's the next thing we'd like to build. 

Our ideas, combined with feedback and requests from early adopters, should help us shape software that people need and that we enjoy building. 

Initially this issue will be quite empty, but let's keep commenting and adding things, and I'll then categorize all the ideas in the OP for better readability. 

Let's gooo 🚀

**Comment by pavlenex** [comment]
- [ ] Monitoring sw in the sv2 code base

**Comment by moneyball** [comment]
I've heard a couple of people say we need to support sv1 pool software. https://discord.com/channels/950687892169195530/1019861139573714994/1020690829548982342

**Comment by moneyball** [comment]
JDP/JD is unspecified and needs miner customer research to determine if it is important and to determine what it is.

**Comment by pavlenex** [comment]
Closing this one, since we now discuss and track our roadmap in dedicated channel on Discord.
