### ISSUE TITLE
C++: Remove the autoconf configuration --enable-template-provider and just pass a port to specify running the TP

### ISSUE THREAD

**Issue by ccdle12** [stratum-mining/stratum#235]
Review from Matt, we should remove the `--enable-template-provider` flag which initializes a preprocessor to switch the TP on and off.

Instead we should just pass a port like `-sv2=8442` to essentially switch the TP on, if the port is empty or omitted, the TP server doesn't run.

**Comment by pavlenex** [comment]
@ccdle12 Should we aim for MVP1 or MVP2 for this one?

**Comment by ccdle12** [comment]
> @ccdle12 Should we aim for MVP1 or MVP2 for this one?

This could be MVP1, it's not a big complicated change. Also, it's probably not the most important one either.
