### ISSUE TITLE
ping-pong-without-noise GitHub Action Hangs Forever

### ISSUE THREAD

**Issue by rrybarczyk** [stratum-mining/stratum#249]
In the `test.yaml` GitHub Action, the `Run ping-pong-without-noise` job hangs forever until it eventually stops and is marked a failure. To avoid hindering development progress, PR #241 comments it out. Fortunately, the `Run ping-pong-with-noise` job passes, and these two applications share most of the same code. However, it is still important to determine the reason why the `Run ping-pong-without-noise` job is failing and for it to be fixed.

Pertinent information:
- [Commit 13e22cb](https://github.com/stratum-mining/stratum/commit/13e22cb75c54a4a4aeb9e4371bd7a6c1702aace4) merged into `main`  is the first instance of the failure. However, in the originating commit in #283, all actions pass just fine. There are no changes made to any action files in this PR.
- For unrelated reasons, commits [ab3bf4c](https://github.com/stratum-mining/stratum/commit/ab3bf4cd88f65b01d381ef8be7a57a676d9e42e0) and [be970c1](https://github.com/stratum-mining/stratum/commit/be970c17aaad46ae55fe5c99aa289aff3ea38726) were merged without running any GitHub Actions. It is assumed that the `Run ping-pong-without-noise` job would be a failure here though.
- The `fuzz-tests` job in [commit 143e1aa](https://github.com/stratum-mining/stratum/actions/runs/3097238497/jobs/5013691505) fails, but is fixed in [commit be8e1e9](https://github.com/stratum-mining/stratum/commit/be8e1e96bfa189502af95f8edb01ad5429945a58). Because the `fuzz-tests` job fails here, the `Run ping-pong-without-noise` job is never executed, but is assumed to be a failure.
- Also in [commit be8e1e9](https://github.com/stratum-mining/stratum/commit/be8e1e96bfa189502af95f8edb01ad5429945a58) is where the `Run ping-pong-without-noise` job  is commented out.

**Comment by xraid** [comment]
i moved sleep in node.rs line 65 or rather comented out //
and added                 
`task::sleep(time::Duration::from_millis(500)).await;`
on line 51
runs on mac and ubuntu -- before the ubuntu did not adhere to `node.last_id > test_count`
somewhere somehow
