### ISSUE TITLE
Binarry-sv2 errors

### ISSUE THREAD

**Issue by Fi3** [stratum-mining/stratum#25]
Errors from [serde-sv2](https://github.com/stratum-mining/stratum/tree/main/protocols/v2/binary-sv2/serde-sv2) and [no-serde-sv2](https://github.com/stratum-mining/stratum/tree/main/protocols/v2/binary-sv2/no-serde-sv2/codec) must be refactored. [Binary-sv2](https://github.com/stratum-mining/stratum/tree/main/protocols/v2/binary-sv2/binary-sv2) should define an Error type that implement from serde-sv2 Error and from no-serde-sv2 Error users should only care about binary-sv2 errors.

**Comment by rrybarczyk** [comment]
We are removing `serde` dependency, so this no longer applies.
