### ISSUE TITLE
On ubuntu the client and server example hangs

### ISSUE THREAD

**Issue by darricksee** [stratum-mining/stratum#253]
The client and server example should be re-enabled and fixed - it is currently not completing in ubuntu - https://github.com/stratum-mining/stratum/actions/runs/3040185392/jobs/4895943816

**Comment by rustynirvana** [comment]
I have a fix for this one, can you assign to me.

**Comment by rustynirvana** [comment]
PR - https://github.com/stratum-mining/stratum/pull/255

**Comment by pavlenex** [comment]
Closing this one as it's been done in #255
