### ISSUE TITLE
SV1/SV2 Translator: Change Diff Target with Upstream Based on Number of Connected Downstreams

### ISSUE THREAD

**Issue by rrybarczyk** [stratum-mining/stratum#257]
1. In the `proxy-config.toml` add a value that represents the expected cumulative hashrate of the Downstream MDs.
2. On Upstream channel open, communicate the hashrate (using the number in the config as we expect that the Downstream MD operator knows already has an idea of their hashpower).
3. On Upstream open channel success, get the target for the translator.
4. Save this target in the `Upstream` struct.
5. Every time a Downstream connects, use that difficulty (so we only send one `mining.set_difficulty` per downstream connection).

**Comment by pavlenex** [comment]
done in #488 #474
