### ISSUE TITLE
SV1/SV2 Translator: Check Downstream Shares Meet Upstream Target Before Submission

### ISSUE THREAD

**Issue by rrybarczyk** [stratum-mining/stratum#259]
before relay share to upstream we neede to check that downstream share meet upstream target (maybe we already do that I didn't check I just put this point here in case we are not doing it) 
Upon receiving a `mining.submit` from a Downstream (SV1 Miner), the `Bridge` (in `bridge.rs`) should check that the received share meets the pdiff set by the Upstream (SV2 Pool) BEFORE translating the `mining.submit` into a `SubmitSharesExtended` for the `Upstream`.

**Comment by ccdle12** [comment]
Is this related to this TODO: https://github.com/stratum-mining/stratum/blob/main/examples/sv1-mining-device/src/client.rs#L91

**Comment by pavlenex** [comment]
Done in #391
