### ISSUE TITLE
Use U256 Types Instead of HexBytes on 32-Byte or Less Values

### ISSUE THREAD

**Issue by rrybarczyk** [stratum-mining/stratum#260]
Wherever the `HexBytes` type is being used on values that are 32 bytes or less, the `U256` type should be used instead. This `U256` type imposes a 32 byte limit.

`HexBytes` is used in logic related to the SV1 protocol. So the impacted directories are `protocols/v1`, `examples/sv1-server-and-client`, and `examples/translator`.

At one point, I was going to impose a 32 byte limit on `HexBytes` and added logic in `protocols/v1/src/utils.rs`. This logic is commented out and should be deleted. Leaving it as a reference if needed for the `U256` type, but may be useless. Note the error though: `BadHexBytesConvert`. This error is also commented out in `protocols/v1/src/utils.rs`. If the `U256` data type logic does not have proper error handling already, please use this error type. But rename it `BadU256Convert`.

**Comment by coleFD** [comment]
@rrybarczyk I can work on tackling this one if that is good with you
