### ISSUE TITLE
SV1/SV2 Translator Proxy: Error Handling

### ISSUE THREAD

**Issue by rrybarczyk** [stratum-mining/stratum#262]
- [x] #320 
- [ ] Mid Term: Handle each `Result` using a match statement and panic on error with a useful panic message.
- [ ] Long Term: Decide which errors should result in the termination of the proxy and which should be passed over so the proxy stays live. We will want to give a Downstream (SV1 MD) some slack, so if it sends one bogus message to the proxy, we continue. But if the proxy is receiving multiple bogus values ("multiple" needs to be defined), we terminate the proxy.

**Comment by xraid** [comment]
maybe a typo :

"We will want to give a Downstream (SV1 MD) some slack, so if it sends one bogus message to the proxy, we continue. But if the proxy is receiving multiple bogus values ("multiple" needs to be defined), we terminate the proxy."

if -one- mining-device sends bogus messages, shut down channel to mining-device and keep proxy running ...
