### ISSUE TITLE
TProxy pub key in config should be string instead of array

### ISSUE THREAD

**Issue by rrybarczyk** [stratum-mining/stratum#297]
Currently `upstream_authority_pubkey` is given in the config as an array of bytes [here](https://github.com/stratum-mining/stratum/blob/914ca6eb4a2576deb94b5bea6d193e4012a9af8f/roles/translator/proxy-config.toml#L4).
Needs to be read in as a string like the sv2-proxy config [here](https://github.com/stratum-mining/stratum/blob/914ca6eb4a2576deb94b5bea6d193e4012a9af8f/roles/v2/mining-proxy/proxy-config.toml#L1).

**Comment by pavlenex** [comment]
Seems this one has been fixed in https://github.com/stratum-mining/stratum/commit/a1472c00c562c506aa4ee379264f0ddeb240ea31 , will re-open if that's not the case @rrybarczyk ?
