### ISSUE TITLE
C++: Implement Template Provider heuristics on when to issue a new template besides from the best global block changing

### ISSUE THREAD

**Issue by ccdle12** [stratum-mining/stratum#310]
Besides the best known global block changing in the Bitcoin Core node e.g. p2p layer receives a new best block, one of the downstream devices finds a best new block. There are other scenarios to consider, a new transaction enters the mempool with a very high fee, we want to issue a new template with this new transaction that increases the overall fee of the block.

**Comment by Fi3** [comment]
Maybe we can send new template every x seconds (with x configurable)

**Comment by Sjors** [comment]
We now send a new template when:
1. a new block is connected; or
2. a) fees increased by `-sv2feedelta`; and
   b) `-sv2interval` seconds went by
   
Longer term goal is to drop (2) but this requires mempool refactoring.

I think this can be closed.
