### ISSUE TITLE
Use rust-bitcoin's U256 method and remove bigint dependency

### ISSUE THREAD

**Issue by rrybarczyk** [stratum-mining/stratum#318]
In the Translator Proxy, we are currently using the archived [bigint](https://crates.io/crates/bigint) library to handing U256 values. We already depend on [rust-bitcoin](https://crates.io/crates/bitcoin) which has a U256 method which we should use instead, then we need to remove the bigint dependency.

**Comment by lorbax** [comment]
I start working on this issue.

**Comment by lorbax** [comment]
This issue has already been solved.
