### ISSUE TITLE
MVP1 Translator Proxy Post-Merge Todos

### ISSUE THREAD

**Issue by rrybarczyk** [stratum-mining/stratum#319]
After the MVP1 Translator Proxy is merged, these are the follow up issues that need to be made:

- [x] #256 
- [x] #260 
- [x] #261 
- [x] #262
- [x] #269 
- [x] #275
- [x] #330 
- [x] #334 
- [x] #335

**Comment by pavlenex** [comment]
@darricksee @bcral Would we be able to tackle these for the MVP 2? Is this list still relevant for important things for getting tProxy in shape, or should we add something to it?

**Comment by darricksee** [comment]
256 is def. needed. 335 is questionable. What is the scaling goal for MVP2? If we are fine with only minimal testing (1-2 miners) then we probably don't even need 256. If we want to remain compatible with braiins then we shouldn't do 335 (I don't think braiins compatibility is important for MVP2)
