### ISSUE TITLE
SV1/SV2 TProxy to support automatic pool fail over on protocol-inconsistent messages

### ISSUE THREAD

**Issue by rrybarczyk** [stratum-mining/stratum#326]
SV1/SV2 Translator Proxy should support automatic fail over to a secondary and tertiary pool if it receives unexpected messages from the Upstream pool.

**Comment by pavlenex** [comment]
@Fi3 did you just solve this one in https://github.com/stratum-mining/stratum/pull/420 ?

**Comment by pavlenex** [comment]
This feature has been added.
