### ISSUE TITLE
SV1/SV2 TProxy to support automatic pool fail over (and solo mine) if pool does not accept miner tx selection

### ISSUE THREAD

**Issue by rrybarczyk** [stratum-mining/stratum#327]
SV1/SV2 Translator Proxy should support automatic fail over to a secondary and tertiary pool if the pool refuses to allow tx selection/rejects templates. If the secondary and tertiary pools also fail for any reason, the default behavior of the proxy should be to solo mine.

**Comment by pavlenex** [comment]
This has been implemented so closing.
