### ISSUE TITLE
Use `shrink` for prop tests

### ISSUE THREAD

**Issue by rrybarczyk** [stratum-mining/stratum#33]
When implementing `Arbitrary` we should also implement `shrink`.

Example from @Fi3:
```
fn shrink(&self) -> Box<dyn Iterator<Item = Self>> {
           let value = self.clone().0;
           match value.template_id {
               0 => empty_shrinker(),
               _ => {
                   let mut shrinked_ids: Vec<NewTemplate> = vec![];
                   for id in 0..value.template_id {
                       let mut shrinked_value = value.clone();
                       shrinked_value.template_id = id;
                       shrinked_ids.push(shrinked_value);
                   };
                   Box::new(shrinked_ids.into_iter().map(|x| RandomNewTemplate(x)))
               }
           }
       }
```

**Comment by rrybarczyk** [comment]
Currently, prop tests use this pattern. We want to make sure people continue to use this pattern, so a `CONTRIBUTING.md` file needs to be added to the repo root stating the expectations for implementing prop tests.

**Comment by Arshia-r-m** [comment]
Hi everybody, I want to give a try for this issue but I need more explanation, which part requires documentation?

**Comment by GitGab19** [comment]
Hey @Arshia-r-m, I think that this issue is outdated since it's very old.
Also I see that the tracker one has been closed years ago: https://github.com/stratum-mining/stratum/issues/112

@rrybarczyk could you confirm?

**Comment by rrybarczyk** [comment]
@GitGab19 and @Arshia-r-m This is super old. @Arshia-r-m if you want, you can look into the code and see if `Arbitrary` is still being used in the tests and if improvements here are still needed. Even just finding examples of the use of `Arbitrary` and posting your findings here for more clarity would be helpful. Thanks!

**Comment by Arshia-r-m** [comment]
I looked the test folder again but I didn't find anything related, so I guessed that I might miss understood the exact meaning of `Arbitrary` here.
Can you please provide me more info on it?

**Comment by rrybarczyk** [comment]
The `test` folder in the project's root is a little misleading. You won't find what you need there.

I did a search for `Arbitrary` and I see it being used in the following files:

- `protocols/v2/sv2-ffi/src/lib.rs`
- `protocols/v2/subprotocols/common-messages/src/lib.rs`
- `protocols/v2/subprotocols/template-distribution/src/lib.rs`
- `protocols/v2/subprotocols/template-distribution/src/new_template.rs`
- `protocols/v2/roles-logic-sv2/src/job_dispatcher.rs`
- `protocols/v2/noise-sv2/src/handshake.rs`
- `protocols/v2/roles-logic-sv2/src/job_creator.rs`
- `protocols/v2/binary-sv2/no-serde-sv2/codec/src/datatypes/non_copy_data_types/mod.rs`
- `protocols/v1/src/methods/client_to_server.rs`
- `utils/buffer/fuzz/fuzz_targets/faster.rs`
- `utils/buffer/fuzz/fuzz_targets/slower.rs`

Taking `protocols/v2/noise-sv2/src/handshake.rs` at random, I see it is used in the `mod test`, imported on L144.

Perhaps looking into how `Arbitrary` is used in these test and looking into best `Arbitrary` practices would be a good start? Verifying that we are using this correctly (if so, we can close this issue), or if there are some best practices we are missing (like using `shrink`). 

Keep in mind, this is a very old issue (opened originally in 2021) and may be out of date. Don't want to send you down too much of a wild goose chase.

**Comment by Arshia-r-m** [comment]
As if I understood correctly, the `Arbitrary` usage is to create random values for testing the different possible inputs in this files?

**Comment by Fi3** [comment]
is used for proptest https://proptest-rs.github.io/proptest/proptest/index.html

**Comment by Arshia-r-m** [comment]
I've checked the mentioned linked and in my opinion, the arbitrary works fine here :)

**Comment by rrybarczyk** [comment]
> I've checked the mentioned linked and in my opinion, the arbitrary works fine here :)

Ok great, will close this issue. Thanks!
