### ISSUE TITLE
Replace future_job with min_ntime in mining job messages

### ISSUE THREAD

**Issue by rrybarczyk** [stratum-mining/stratum#335]
There has been a [spec change](https://github.com/stratum-mining/sv2-spec/pull/12) that removes the `future_job` field from the mining job messages and replaces it with `min_ntime`. The affected files are:

- [ ] `protocols/v2/roles-logic-sv2`
- [ ] `protocols/v2/subprotocols/mining`
- [ ] `protocols/v2/subprotocols/template-distribution`
- [ ] Pool: `roles/v2/pool`
- [ ]  SV2 MD: `roles/v2/test-utils/mining-device` 
- [ ] SV1/SV2 Translator proxy: `roles/translator`

**Comment by pavlenex** [comment]
This has been done in #503
