### ISSUE TITLE
Add a configurable "insecure connections" feature 

### ISSUE THREAD

**Issue by darricksee** [stratum-mining/stratum#339]
Currently the pool role only allows incoming connections that are encrypted via the noise protocol. During development/debugging it's often useful to be able to work with an unencrypted channel. The solution is to make the encrypted channel optional via configuration. This configuration "accept_insecure_connections" should allow for insecure connections to be made and communicated on. The idea is that this configuration option would always be false in production environment but could be true in test. If it is true a downstream connection can be made either via noise or not.

**Comment by xraid** [comment]
This is also needed or would ease for edge case configurations, for example BraidPool could use SRI proxy to then forward to local-net p2p network micro-service with its chosen transport while not having to fork and mod the SRI proxy, instead just configure "accept_insecure_connections", or call it `use_noice: bool `

**Comment by ccdle12** [comment]
In principle, yes I agree - for easier testing and development. I just hope/would like to eliminate the possibility of users opting to switch this feature off for xyz reasons. All communication for handling work/submissions should be secure.
