### ISSUE TITLE
Undocumented Source-less Unsigned Binaries

### ISSUE THREAD

**Issue by xraid** [stratum-mining/stratum#350]
stratum-mining/stratum/test/bin 
contains binaries that are undocumented source-less and unsigned

besides documenting what the binaries contain -with what versions, and -how to compile accompanying sources + signed by the project owner, could make any project binaries transparent.

-have a separate repository for binaries, be it test or release ? 

-we trust -it is made easy for each and everybody to verify ...

**Comment by pavlenex** [comment]
I think this one can be closed since #360 is the new tracker for it.
