### ISSUE TITLE
Translator insists on version_bits

### ISSUE THREAD

**Issue by Sjors** [stratum-mining/stratum#362]
See Discourse discussion in #newbie-qs.

When testing the translator with [pooler/cpuminer](https://github.com/pooler/cpuminer) it complains `Err value: NoSv1VersionBits`. It also seems the Slushpool upstream disconnects at this point.

Is this intentional?

**Comment by Fi3** [comment]
I think is a translator bug: 
mining-deivce signal that is not going to change version bits but translator expect version bits to be set @rrybarczyk can you look into it?

**Comment by coleFD** [comment]
@Fi3 I think you are right. Based on this BIP it looks like clients are only guaranteed to send `version_bits` with `mining.submit` if they are configured for version rolling (https://en.bitcoin.it/wiki/BIP_0310). Here it returns the error if the version bits arent set https://github.com/stratum-mining/stratum/blob/main/roles/translator/src/proxy/bridge.rs#L123. 

@rrybarczyk would it make sense to store a mapping for `job_id -> version` in the `Bridge` to insert the version, sent with the job, for clients that arent version rolling?
