### ISSUE TITLE
Translator proxy target management loop needs a channel

### ISSUE THREAD

**Issue by darricksee** [stratum-mining/stratum#385]
The [downstream struct in the translator proxy currently consumes a thread doing nothing most of the time](https://github.com/stratum-mining/stratum/blob/main/roles/translator/src/downstream_sv1/downstream.rs#L162). In the task that waits for a target change it just spins forever in an infinite loop locking/unlocking without any waits. I think this will entirely consume a thread and worse cause lock contention with other downstream objects. 

This should be changed to wait on a target channel and have that channel send/receive the new target instead of operating on a shared vec.

**Comment by coleFD** [comment]
I think this can be closed
