### ISSUE TITLE
Common messages as result in open_standard_mining_channel in pool-sri-test-1.json

### ISSUE THREAD

**Issue by lorbax** [stratum-mining/stratum#410]
In /test/message-generator/pool-sri-test-1.json there is an action relative to the message id open_standard_mining_channel. The action sends this message to the pool and checks that the reply should be MiningProtocol and OpenStandardMiningChannelSuccess. Instead of MiningProtocol, why there isn't a message in CommonMessages?

**Comment by pavlenex** [comment]
@Fi3 I guess you may be the one to answer this?
