### ISSUE TITLE
Technical debt .unwrap()

### ISSUE THREAD

**Issue by xraid** [stratum-mining/stratum#428]
When is a good time do away with `.unwrap()` in code

 `.unwrap()` == “Give me the result of the computation, and if there was an error, just panic and stop the program.”

There is 1372 matches of `.unwrap()` across 81 files

**Comment by xraid** [comment]
"Activities that might be postponed include [documentation](https://en.wikipedia.org/wiki/Documentation), writing [tests](https://en.wikipedia.org/wiki/Test_automation), attending to [TODO comments](https://en.wikipedia.org/wiki/Comment_(computer_programming)#Tags) and tackling compiler and [static code analysis](https://en.wikipedia.org/wiki/Static_code_analysis) warnings. Other instances of technical debt include knowledge that isn't shared around the organization and code that is too confusing to be modified easily."

**Comment by pavlenex** [comment]
Closing since it is tracked in https://github.com/stratum-mining/stratum/issues/736 so let's track it there.
