### ISSUE TITLE
There is a DOS vulnerability in the downstream reader

### ISSUE THREAD

**Issue by darricksee** [stratum-mining/stratum#429]
During this bug fix user djozis found a vulnerability - when reading from the downstream connection we basically try to read everything that is put on the pipe. We should read in chunks and process and if in the processing we discover that it's garbage we should drop the connection.

Context:
https://github.com/stratum-mining/stratum/pull/426#discussion_r1092283449

**Comment by Fi3** [comment]
This is not done. #504 solve it but is very old, maybe make sense to close it and open a new PR
