### ISSUE TITLE
Figure out if we can avoid the codecov upload error that we get.

### ISSUE THREAD

**Issue by darricksee** [stratum-mining/stratum#444]
Occasionally we get an upload error from codecov ([example](https://github.com/stratum-mining/stratum/actions/runs/4196180202/jobs/7276789611)) - I think this happens when there are a lot of tests running near each other and we get throttled for too many uploads over a short amount of time. It'd be great to remove this throttle somehow.

**Comment by xraid** [comment]
maybe this is it and will help :

https://github.com/codecov/codecov-action/issues/598

**Comment by darricksee** [comment]
Yep - I followed that same thread but didn't act on it. This would be a great first issue.

**Comment by tusharv01** [comment]
please assign this to me

**Comment by tusharv01** [comment]
yes i have solved that.
