### ISSUE TITLE
Realize Proxy

### ISSUE THREAD

**Issue by Fi3** [stratum-mining/stratum#45]
# Realize Proxy

## What
Realization of a proxy that is:
* configurable (easy to configure for the wanted scenario via config files)
* efficient (it must be fast)
* expandable (it must be easy to modify the code in order to add new supported scenarios)
* easy to use (deploy the proxy must be very easy)

## Why
TODO

## How
- [x] #46
- [ ] #91
- [ ] #92
- [ ] #93
- [ ] #94
- [ ] #95
- [ ] #96

**Comment by rrybarczyk** [comment]
This project plan is out of date.
