### ISSUE TITLE
Cargo install

### ISSUE THREAD

**Issue by Sjors** [stratum-mining/stratum#450]
It would be nice to get the binaries in `~/.cargo/bin`, but when I run `cargo install` currently I get:

```
error: found a virtual manifest at `/home/stratum/src/stratum/Cargo.toml` instead of a package manifest
```

I'm not familiar enough with Rust and Cargo to know what the issue is here.

**Comment by plebhash** [comment]
I just did `cargo install --path .` on all roles and seems to be working fine
