### ISSUE TITLE
Update all `ed25519-dalek` dependency to a published version

### ISSUE THREAD

**Issue by coleFD** [stratum-mining/stratum#458]
We cannot publish crates that have github dependencies, and because we need `no_std` support, we are currently depending on a fork of the original ed25519-dalek repo since the published version will not compile. We need to find a solution to point towards a published crate in `noise_sv2`, so we can publish the crate and the crates that depend on `noise_sv2`.

**Comment by coleFD** [comment]
So apparently version `2.0.0-pre.0` is out now and is "supposed" to be compatible with no_std, but the `curve25519-dalek` crate version is incompatible with the one used by `snow` which is another `noise_sv2` dependency. There is a possibility that we can get snow to bump their `curve25519-dalek` dependency to the same one used by `ed25519-dalek`. With that being said, we need to confirm that the `2.0.0-pre.0` version is actually no_std compatible. Also as a note, the pre-release version has an updated api so we will need to adjust the `noise_sv2` crate to match.

Wrt the `toml` dependencies (https://github.com/stratum-mining/stratum/issues/456) forking and publishing may be the only way to go. I dont see this as a big issue since we only use it to parse config files.

**Comment by pavlenex** [comment]
@Fi3 pointed out @lorbax could look into this to see if we use it, if not we can close it.

**Comment by pavlenex** [comment]
> the curve ed25519-dalek was abondoned in favor of secp256k1
