### ISSUE TITLE
mining-proxy needs graceful death instead of panic

### ISSUE THREAD

**Issue by bcral** [stratum-mining/stratum#484]
The mining-proxy seems to be panicking on closure.  This makes test coverage data impossible to retrieve with llvm-cov.

This same issue used to exist on the pool and TProxy until it was fixed by #432

**Comment by bcral** [comment]
Please tag as "good first issue"!

**Comment by Priceless-P** [comment]
@bcral i’d like to work on this.

**Comment by Priceless-P** [comment]
@bcral Just to be sure, [this](https://github.com/stratum-mining/stratum/blob/main/roles/v2/mining-proxy/src/main.rs) is the file that needs to be worked on for this issue right?

**Comment by darricksee** [comment]
I haven't and probably won't get to it soon.

**Comment by darricksee** [comment]
Just a heads-up @Priceless-P  - to implement this the `status-channel` also needs to be added to the mining-proxy before getting to this issue. You can certainly add both with this issue - [take a look at how the `status-channel` is used in the pool role](https://github.com/stratum-mining/stratum/blob/main/roles/v2/pool/src/main.rs#L226). It's basically a mechanism for the application to signal the main thread to terminate if one of the tasks has an error.

**Comment by Priceless-P** [comment]
Okay. Thank you for letting me know. @darricksee

**Comment by SumantxD** [comment]
@bcral i would like to work on this issue, can you assign it to me.

**Comment by Priceless-P** [comment]
Hi @SumantxD, I am currently working on it.

**Comment by SumantxD** [comment]
@Priceless-P ok fine

**Comment by mihir1739** [comment]
Hey is anyone working on this issue ? If not please assign this to me .

**Comment by pavlenex** [comment]
Hey @mihir1739 it seems @Priceless-P is working on it here https://github.com/stratum-mining/stratum/pull/518

**Comment by plebhash** [comment]
@Priceless-P what is the status on this? why was #518 closed without being merged?

**Comment by Priceless-P** [comment]
@plebhash Yes.

**Comment by johnnyasantoss** [comment]
Is this up for grabs? @Priceless-P
