### ISSUE TITLE
Refactor Errors

### ISSUE THREAD

**Issue by Fi3** [stratum-mining/stratum#50]
# Refactor Errors
Errors in the low level crates are not well designed. That because it would have been much more effective to
design them when the low level crates are functionally complete tested and used in other crates.
So all the Error(s) in the project must be refactored.

- [x] #51
- [ ] #52 that means that each TODO is either:
        1. resolved
        2. removed
        3. transformed into github issues
- [x] #78

## Useful links
* http://sled.rs/errors.html

**Comment by rrybarczyk** [comment]
- [x] `roles-sv2-logic` #229 
- [x] `framing-sv2` #227 
- [x] `codec-sv2` #195
- [x] `binary-sv2` #195
- [ ] `subprotocols`, not too many places where this can error (@lorban is working on this)
- [ ] double check `roles` crates for potential error handling needs, but believe most unwraps are infallible
- [ ] double check `examples` are doing error handling properly
