### ISSUE TITLE
Pool/TP messages out of order with SRI spec

### ISSUE THREAD

**Issue by bcral** [stratum-mining/stratum#516]
After reviewing the MG tests, it seems that the Set New Previous Hash message is being received by the downstream before New Mining Job when the hosted TP is used with the pool_sv2 role.  This is opposite of how it is shown here in the spec: https://github.com/stratum-mining/sv2-spec/blob/main/05-Mining-Protocol.md
This is partially masked by some tests using a mock TP, which seems to pass the messages to the downstream in the correct order.

**Comment by darricksee** [comment]
fixed with https://github.com/stratum-mining/stratum/pull/522
