### ISSUE TITLE
Autoversion PR workflows cannot be executed

### ISSUE THREAD

**Issue by coleFD** [stratum-mining/stratum#517]
Do to GH security concerns, workflows cannot be initiated on PRs from GH bots. See https://github.com/peter-evans/create-pull-request/issues/48 for possible solutions. Other solutions would be to find a way to allow maintainers to initiate the workflow manually or to just remove the need to run workflows on the `bot/versioning` branch. The last approach would require us to review PRs on this branch to ensure devs are not changing logic on this branch.

**Comment by plebhash** [comment]
we don't have `autoversion.yaml` anymore, therefore this issue is no longer relevant
