### ISSUE TITLE
Create SV2 Pool Application

### ISSUE THREAD

**Issue by Fi3** [stratum-mining/stratum#53]
# Realize Pool
## What
Realization of a pool that can be used in production environment 
* efficient (it must be fast)
* easy to use (deploy the pool must be very easy)

## Why
In order for Sv2 to succeed, operational cost for a pool to support it must be low, and implementation cost must be near 0.

## How
- [x] #97
- [ ] #98
- [x] #99
- [x] #100
- [x] #101
- [x] #102
- [x] #103

**Comment by pavlenex** [comment]
I am going to close this tracker issue since there's only one issue remaining #98 and it's still unclear when it will be needed, closing to avoid duplication in issues, no need to have issue that track a single issue.
