### ISSUE TITLE
Deploy `safe pool` hosted by SRI community 

### ISSUE THREAD

**Issue by pavlenex** [stratum-mining/stratum#554]
SRI should offer a last-resort pool that will be used by JNClient as an upstream if all other upstreams refuse the proposed jobs. This pool should not have any fees associated with it.

**Comment by rsantacroce** [comment]
that's very very good, what would be a good domain name to have it just in case we want to deploy this soon ? 
i have some spare space on my data center that i can definetly use to bootstrap the thing.

**Comment by moneyball** [comment]
How are custodied funds handled?

**Comment by rsantacroce** [comment]
It's an open question but for sure the spec save space for it as an extention, i think there will be diff implementations as usual:
- braidpool had an idea using DAG now they are onto frost and etc.
- there is the potential to have a sidechain to deal with this specially if we end up having BMM 
- mayve a fedimint style, or something like that .... 

Looking forward to brainstorm this !

**Comment by EthnTuttle** [comment]
> How are custodied funds handled?

fedimint seems like a north start for this.

happy to discuss further. or join chat.fedmint.org

**Comment by pavlenex** [comment]
We kinda gave up on this idea we just didn't close the issue.

We as "SRI" project/community just don't have capacity to do this, and that's what issue was far. Nobody wants to handle a company or legal risks, let alone be custodian and in a way we have other things we want to focus on - developing software.

I think what @rsantacroce is actually referring, after looking at our DM's is to is that a mining facility he's a part of can deploy a pool and test things out, which is always welcomed!

There's also a [RFC for non-custodial pool](https://x.com/StratumV2/status/1654481713005838337?s=20) payouts by @lorbax @rrybarczyk and @Fi3, but it requires APO and some more work on it.
