### ISSUE TITLE
Add RequestTransaction data handler to bitcoind

### ISSUE THREAD

**Issue by Fi3** [stratum-mining/stratum#565]
When the TP receive `RequestTransaction` it MUST answer with either  `RequestTransactionSucess` or  `RequestTransactionError` 

priority 9/10

**Comment by ccdle12** [comment]
Try this branch: https://github.com/ccdle12/bitcoin/tree/2023.06.29-request-data-msg

I didn't have time to test against the SRI, let me know if any fixes required

**Comment by Fi3** [comment]
@ccdle12 not sure why you put the `commitment_hash` in the `excess_data` field. This seems unnecessary to me, can you explain why we need it? Ty

**Comment by ccdle12** [comment]
> @ccdle12 not sure why you put the `commitment_hash` in the `excess_data` field. This seems unnecessary to me, can you explain why we need it? Ty

I interpreted this from the specs: https://github.com/stratum-mining/sv2-spec/blob/main/07-Template-Distribution-Protocol.md#75-requesttransactiondatasuccess-server-client

```
 response to RequestTransactionData which contains the set of full transaction data and excess data required for validation. For practical purposes, the excess data is usually the SegWit commitment,
 ```

**Comment by Fi3** [comment]
IMO this is unnecessary the txs data are sent to the JDS and the JDS will calculate the the commitment on block creation. No need to send it there.

**Comment by ccdle12** [comment]
> IMO this is unnecessary the txs data are sent to the JDS and the JDS will calculate the the commitment on block creation. No need to send it there.

Ok thats fair, maybe we should consider updating the specs so other users don't think its expected

**Comment by pavlenex** [comment]
@Fi3 could you please file an issue for this in specs repo?

**Comment by Fi3** [comment]
Maybe is better if @ccdle12 just open a PR for it

**Comment by ccdle12** [comment]
Ok no problem, talked to @Fi3 , I'll switch it to the witness reserve value

**Comment by pavlenex** [comment]
Do we still want to change anything in specs to clarify this or? Just making sure.

**Comment by ccdle12** [comment]
@Fi3 updated to return witness return value: https://github.com/ccdle12/bitcoin/tree/2023.06.29-request-data-msg

**Comment by Sjors** [comment]
Anything left to do here? https://github.com/bitcoin/bitcoin/pull/28983 returns `Sv2RequestTransactionDataSuccessMsg`.

**Comment by Fi3** [comment]
I think that we can close it, I let it open also for others to review @GitGab19 @lorbax
