### ISSUE TITLE
Add encryption and new framing to bitcoind

### ISSUE THREAD

**Issue by Fi3** [stratum-mining/stratum#566]
The TP MUST implement the new framing, and MUST be able to open encrypted connections.

## Resources:
1. [new framing PR](https://github.com/stratum-mining/sv2-spec/pull/40)
2. [new framing issue](https://github.com/stratum-mining/sv2-spec/issues/31)
3. [noise](https://github.com/stratum-mining/sv2-spec/blob/main/04-Protocol-Security.md)

priority 8/10

**Comment by pavlenex** [comment]
This one should be complete now.
