### ISSUE TITLE
Fix NewTemplate.merkle_path in bitcoind

### ISSUE THREAD

**Issue by Fi3** [stratum-mining/stratum#567]
` NewTemplate.merkle_path` should be the smaller path possible needed to calculate the merkle root given the coinbase tx. Right now is composed by all the tx ids of the txs that are in the candidate block.

priority 6/10

**Comment by pavlenex** [comment]
@Fi3 I think we fixed this one?

**Comment by Sjors** [comment]
I think that's why the helper function `GetMerklePathForCoinbase(const CBlock& block)` was added to https://github.com/bitcoin/bitcoin/pull/28983

If that's correct then this issue can be closed. It needs some refactoring, but that doesn't have to be tracked here.

**Comment by Fi3** [comment]
yep is correct.
