### ISSUE TITLE
Automatize version increment

### ISSUE THREAD

**Issue by Fi3** [stratum-mining/stratum#58]
# Automatize version increment

## Useful links:
* https://towardsdatascience.com/setup-version-increment-and-automated-release-process-591d87ea1221

**Comment by pavlenex** [comment]
I believe this one is done with https://github.com/stratum-mining/stratum/blob/main/RELEASE.md ? @Fi3 @plebhash ?

**Comment by plebhash** [comment]
version increment is not automated
