### ISSUE TITLE
Role Refactor -  A mining-proxy that is a pure Sv2 proxy that only does downstream aggregation/load balancing.

### ISSUE THREAD

**Issue by pavlenex** [stratum-mining/stratum#589]
Follow up from #555

**Comment by plebhash** [comment]
@pavlenex is this still relevant? I wasn't around when this discussion happened, but since we have a working proxy, I assume this issue is obsolete?

**Comment by pavlenex** [comment]
I think this idea originates from having an actual SV2 proxy, there hasn't been much discussion about this, we can close it or leave as a to-do for the future.
