### ISSUE TITLE
add benchmarks

### ISSUE THREAD

**Issue by Fi3** [stratum-mining/stratum#59]
# Add benchmarks

## Useful links:
* http://blog.pnkfx.org/blog/2021/04/26/road-to-turbowish-part-1-goals/

**Comment by pavlenex** [comment]
This old issue seems to be lacking a lot of context, but I assume it relates to benchmarking tool we've made already https://github.com/stratum-mining/benchmarking-tool or relating to benches in PR's which we also have. If this is something else, let's add more context and re-open it.
