### ISSUE TITLE
Finalize Sv2 2022 project plan

### ISSUE THREAD

**Issue by Fi3** [stratum-mining/stratum#60]
Tracking issue

**Comment by Fi3** [comment]
## Sv2 Project Plan 2022
[Sv2 Project Plan 2022.pdf](https://github.com/stratum-mining/stratum/files/7582792/Sv2.Project.Plan.2022.pdf)

## Sv2 Project Plan 2021
[Sv2 Project Plan 2021.pdf](https://github.com/stratum-mining/stratum/files/7582796/Sv2.Project.Plan.2021.pdf)
 
## Sv2 Specifications
[Stratum V2 Specification.pdf](https://github.com/stratum-mining/stratum/files/7582823/Stratum.V2.Specification.pdf)

## Sv2 Overview
https://docs.google.com/document/d/1efN1JnAGiTw96LtfP70BngtP49SLtbMahPYSROfiMqA/edit#

**Comment by pavlenex** [comment]
Verified with @Fi3 that this issue is now considered completed.
