### ISSUE TITLE
Template Provider is not dividing messages payloads into chunks before encryption/decryption

### ISSUE THREAD

**Issue by GitGab19** [stratum-mining/stratum#687]
As defined [here](https://github.com/stratum-mining/stratum/blob/b0eb6db9f0318c94654887a34b186e8533470681/protocols/v2/const-sv2/src/lib.rs#L9C1-L9C47), payloads of sv2 messages must be divided into chunks of specific length defined as it follows: 

`pub const SV2_FRAME_CHUNK_SIZE: usize = 65519;`

⚠️ The problem here is that TP we're referring to for this issue (https://github.com/ccdle12/bitcoin/tree/2023.10.09-new-header-formatting) is not doing that before encypting/decrypting sv2 messages. So it can happen that messages which TP sends to other roles, are not correctly interpreted by the other roles, so that everything is broken.

In order to let it work during our internal testing phase, we're manually changing the constant value mentioned before (https://github.com/stratum-mining/stratum/blob/b0eb6db9f0318c94654887a34b186e8533470681/protocols/v2/const-sv2/src/lib.rs#L9C1-L9C47) with `SV2_FRAME_CHUNK_SIZE: usize = 65519000000000;`

✅ To solve this issue, the TP should be fixed in order to divide in chunks defined by the correct constant value (65519).

**Comment by Sjors** [comment]
This should work now.
