### ISSUE TITLE
JDS panics after ProvideMissingTransactionsSuccess with invalid index

### ISSUE THREAD

**Issue by GitGab19** [stratum-mining/stratum#703]
While looking at our Pool & JDS logs, it happened a panic on JDS. 
Don't know how I could eventually cause it, however I think we should avoid to panic there.
The line of interest is [`roles/jd-server/src/lib/job_declarator/message_handler.rs:153:30`](https://github.com/stratum-mining/stratum/blob/83ad5119839dea49f78b251fbad7b5c694a44072/roles/jd-server/src/lib/job_declarator/message_handler.rs#L153)

As suggested by @Fi3, it should just close the connection in that case.

Here's a screenshot of Pool & JD-Server logs error.

<img width="2556" alt="Screenshot 2023-12-20 at 12 08 18" src="https://github.com/stratum-mining/stratum/assets/62447440/896ca06d-72a4-434e-af9d-2c7ee89545b0">

**Comment by Fi3** [comment]
https://github.com/stratum-mining/stratum/pull/710/files
