### ISSUE TITLE
JDS panics after client disconnection

### ISSUE THREAD

**Issue by GitGab19** [stratum-mining/stratum#707]
Sometimes, after a JD-Client disconnects, the JD-Server panics.
The line of interest is [roles/jd-server/src/lib/job_declarator/mod.rs:102:79](https://github.com/stratum-mining/stratum/blob/83ad5119839dea49f78b251fbad7b5c694a44072/roles/jd-server/src/lib/job_declarator/mod.rs#L102).

Here's a screenshot of the error, for better context.
<img width="1278" alt="Screenshot 2024-01-02 at 17 37 14" src="https://github.com/stratum-mining/stratum/assets/62447440/2b8c18c4-8e0b-41e3-b50f-30b831ba3a49">

**Comment by Fi3** [comment]
https://github.com/stratum-mining/stratum/pull/710/files
