### ISSUE TITLE
Pool panics after receiving an UpdateChannel message

### ISSUE THREAD

**Issue by GitGab19** [stratum-mining/stratum#712]
Pool panics after an` UpdateChannel` message is received, and takes to a `TargetError(NegativeInput)`.
It seems that something should be implemented in the code yet.
The line of interest is [roles/pool/src/lib/mining_pool/mod.rs:192:17](https://github.com/stratum-mining/stratum/blob/d5659cb8a934a0dc1e76bd7930bd02098e7e395f/roles/pool/src/lib/mining_pool/mod.rs#L192).

Here's a screenshot of the error, for a better context:
<img width="1251" alt="Screenshot 2024-01-08 at 11 33 46" src="https://github.com/stratum-mining/stratum/assets/62447440/3128147c-f012-4206-bc01-1d379c9cbd2b">

**Comment by plebhash** [comment]
@GitGab19 any tips on how to reproduce this error?

**Comment by GitGab19** [comment]
> @GitGab19 any tips on how to reproduce this error?

I got it sometimes while testing with asic miner.
The translator automatically adjusts downstream difficulty in order to set the target share_per_minute set in the config file.
But at the same time, it modifies also the upstream difficulty. 
If the miner stops working, the upstream difficulty can become negative.

I dig into it and I will open a PR to fix this tomorrow

**Comment by plebhash** [comment]
ok, let me know if you need help, I can try to reproduce and find a solution as well
