### ISSUE TITLE
SRI uses incorrect encoding of secp256k1 public keys

### ISSUE THREAD

**Issue by jakubtrnka** [stratum-mining/stratum#721]
The specification says that public key should be encoded as 
concatenation of array `[1, 0]` (which is version number) and 32 bytes x-only public key.
using base58-check algorithm

Currently it does direct base58 encoding of the 32 bytes public key without checksum.

See:
https://github.com/stratum-mining/sv2-spec/blob/main/04-Protocol-Security.md#47-url-scheme-and-pool-authority-key

**Comment by Sjors** [comment]
Ah, that's useful to know. I'll switch the correct encoding on the Bitcoin Core side after #722 is merged.
