### ISSUE TITLE
Incorrect use of ECDH result for establishing shared secret

### ISSUE THREAD

**Issue by jakubtrnka** [stratum-mining/stratum#723]
SRI codebase uses `SharedSecret::new()` code for constructing shared secret:
```rust
        let res = SharedSecret::new(&x_public.public_key(crate::PARITY), &private);
        res.secret_bytes()
```

This is against standard, because internally this method takes x & y coordinate of the resulting EC point and calculates sha256 hash.
It is wrong because hashing the y-coordinate into the result makes the result dependent on key parity of either participants.

Correctly only the X coordinate should be taken. Without hashing:
```rust
        let ec_point_x_y = secp256k1::ecdh::shared_secret_point(
            &x_public.public_key(secp256k1::Parity::Even),
            &private,
        );
        let mut ec_point_x = [0; 32];
        ec_point_x.copy_from_slice(&ec_point_x_y[0..32]);
        ec_point_x
```

**Comment by GlitchyBritches** [comment]
This bug does not surprise me, the reference implementation is generally quite poor quality - so I would not trust any security critical code they've implemented

**Comment by pavlenex** [comment]
Hi @GlitchyBritches care to elaborate what's poor quality in the reference implementation? Did you try it out? Tried to implement it or something else? Would be great if you can provide some more feedback so we can learn what needs to be improved?

**Comment by GlitchyBritches** [comment]
Yes I've been implementing it. And there's a lot that's low quality about it. I'll provide a full list, but starting off:

* Littering of "todos!" and "unimplemented!" all over the place
* Littering of key functions in the "main" files which should be logically organized into a struct
* Fragile parsing logic implemented in the main.rs files + reference to github repos for perfectly stable crates

I'll provide a full list with examples when I have time, but were I to do a reference implementation - I would have been embarrassed to release this publicly.

**Comment by moneyball** [comment]
Which branch of code are you referring to?

**Comment by pavlenex** [comment]
Thanks @GlitchyBritches. 

As @moneyball asked, it would be important to know for context which branch you've tried out, since all of our work is on `dev` and will be merged into `master` after months of work, which addresses at least a few of those you listed, though I'd love to learn what else can be improved, as it's important feedback.

Are you on [our Discord](https://discord.gg/fsEW23wFYs)? Perhaps we can continue conversation there and provide you with instructions which aren't published yet on how to run things on `dev`.

**Comment by jakubtrnka** [comment]
I'd also add that the SRI code is very unstable and not very robust. There is lot of unwraps or expects.
It's quite difficult to run it without crashing.
Correctly written rust application should never crash with panic. All error states should be handled and application should either recover or terminate gracefully.

**Comment by Fi3** [comment]
can you provide specific example of when it crash but it shouldn't so we can fix it? ty
Maybe in another issue cause we are off topic here.

**Comment by GlitchyBritches** [comment]
> since all of our work is on dev and will be merged into master after months of work, which addresses at least a few of those you listed, though I'd love to learn what else can be improved, as it's important feedback.

Yes I will provide specific recommendations when I have time in a separate issue. The core protocol is certainly the right abstraction, but the implementation is a poor experience for anyone actually trying to conform the V2 standard. I'll publish a list in the issues within the next 2 weeks as time allows.

**Comment by moneyball** [comment]
@GlitchyBritches can you confirm whether you are looking at/using the code in main or the dev branch?

**Comment by pavlenex** [comment]
Hey @GlitchyBritches Any news? We've merged dev into `main` branch last week, so would be helpful to know your feedback after reviewing that.
