### ISSUE TITLE
Incorrect order of arithmetic operations during handshake

### ISSUE THREAD

**Issue by jakubtrnka** [stratum-mining/stratum#728]
EncryptWithAd is defined in the noise-specification the following way:

```
EncryptWithAd(ad, plaintext): If k is non-empty returns ENCRYPT(k, n++, ad, plaintext). Otherwise returns plaintext.
```
That means the `n` is incremented **after the ENCRYPT operation has been performed**.

SRI, however performs this prior to the ENCRYPT (or DECRYPT) operations:
https://github.com/stratum-mining/stratum/blob/3f07a6a747ab69c1594a93fdc563f06f72d716d8/protocols/v2/noise-sv2/src/cipher_state.rs#L66

https://github.com/stratum-mining/stratum/blob/3f07a6a747ab69c1594a93fdc563f06f72d716d8/protocols/v2/noise-sv2/src/cipher_state.rs#L45

That results in handshake failure.

references:

https://noiseprotocol.org/noise.html#the-cipherstate-object

https://github.com/stratum-mining/sv2-spec/blob/main/04-Protocol-Security.md#441-cipherstate-object

**Comment by Sjors** [comment]
We should also clarify this in the spec.

**Comment by pavlenex** [comment]
@Sjors Should we log an issue in specs repo not to forget to clarify this a bit better in specs?

**Comment by Sjors** [comment]
@pavlenex yes, you could even just make a pull request that adds the sentence from the Noise paper:

> The ++ post-increment operator applied to n means "use the current n value, then increment it"

**Comment by pavlenex** [comment]
Done in #729
