### ISSUE TITLE
Improve error message when JDS can't connect to a local TP

### ISSUE THREAD

**Issue by pavlenex** [stratum-mining/stratum#730]
For JDS a local Template Provider needs to run first otherwise this happens:

```2024-01-23T09:21:59.598808Z  INFO jd_server: Jds INITIALIZING with config: "jds-config.toml"
2024-01-23T09:21:59.599341Z  INFO jd_server::lib::job_declarator: JD INITIALIZED
thread 'tokio-runtime-worker' panicked at jd-server/src/lib/mempool/mod.rs:60:77:
called `Result::unwrap()` on an `Err` value: JsonRpc(Transport(SocketError(Os { code: 61, kind: ConnectionRefused, message: "Connection refused" })))
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'tokio-runtime-worker' panicked at jd-server/src/lib/mempool/mod.rs:75:14:
called `Result::unwrap()` on an `Err` value: JoinError::Panic(Id(10), ...)
```

We should ensure a better error message is presented to the user. Problem is that JDS can't connect to TP to local TP for a few reasons, and we have no way apparently to know what are these reasons  (TP not fully synced, TP down).

Suggested message could be: `Unable to connect to TP (possible reasons: not fully synced, down)`

**Comment by GitGab19** [comment]
I would add that another issue is that the JDS mempool is updated every 10 seconds, which are hardcoded [here](https://github.com/stratum-mining/stratum/blob/3f07a6a747ab69c1594a93fdc563f06f72d716d8/roles/jd-server/src/main.rs#L183).
The update rate should be configurable by the user. 
I'm working on fixing both issues, I will open a PR soon

**Comment by GitGab19** [comment]
> I would add that another issue is that the JDS mempool is updated every 10 seconds, which is hardcoded [here](https://github.com/stratum-mining/stratum/blob/3f07a6a747ab69c1594a93fdc563f06f72d716d8/roles/jd-server/src/main.rs#L183). The update rate should be configurable by the user. I'm working on fixing both issues, I will open a PR soon

I fixed them here: https://github.com/stratum-mining/stratum/pull/727
