### ISSUE TITLE
better import for libsecp256k1

### ISSUE THREAD

**Issue by lorbax** [stratum-mining/stratum#749]
As suggested by @Fi3 in the review of https://github.com/stratum-mining/stratum/pull/737, we should
 1. move the dependency of secp256k1 in stratum_common and import this library from there
 2. avoid to import secp256k1 in roles (it is used by the JDS for signing tokens and by the pool for verifying tokens' signature). Rather, some sort of wrapper structure in roles-logic for making and verifying signatures would be more appropriate.

**Comment by rockcoolsaint** [comment]
I think this is something I can handle. Can I go ahead with it? @lorbax

**Comment by lorbax** [comment]
Don't know if it is really a good "first issue" but if feel comfortable you can DM on discord and discuss how to proceed

**Comment by Fi3** [comment]
now you can import libs from the workspace Cargo.toml and refer to it in the crate Cargo.toml when you have common dep between crates in the same workspace.

**Comment by rockcoolsaint** [comment]
> Don't know if it is really a good "first issue" but if feel comfortable you can DM on discord and discuss how to proceed

What's your discord handle?

**Comment by plebhash** [comment]
closed via #894
