### ISSUE TITLE
Make code more robust starting from good error management

### ISSUE THREAD

**Issue by lorbax** [stratum-mining/stratum#773]
As previously remarked, the SRI codebase should be more robust. For this reason, it may be good to improve the error management and try to avoid catch-all in pattern-matching. Here are two examples
[https://github.com/stratum-mining/stratum/blob/main/roles/pool/src/lib/status.rs#L120](https://github.com/stratum-mining/stratum/blob/main/roles/pool/src/lib/status.rs#L120)
[https://github.com/stratum-mining/stratum/blob/main/roles/pool/src/lib/mining_pool/mod.rs#L382](https://github.com/stratum-mining/stratum/blob/main/roles/pool/src/lib/mining_pool/mod.rs#L382)
The pool should never panic, in general.

Thanks to @Fi3  for pointing this out.

**Comment by Fi3** [comment]
issue [here](https://github.com/stratum-mining/stratum/blob/main/roles/pool/src/lib/status.rs#L120) is not that we panic but that we treat all the `PoolError::RolesLogic(_)` in the same way, and we just exit the process without panicing. This lead to shutdown the pool when a connection initialization with downstream fail. This open the possibility to a DOS attack where clients can easly bring down a pool!

**Comment by Fi3** [comment]
Of course this is not an issue if the pool is only used for testing purposes.

**Comment by Fi3** [comment]
There are situation where is ok to exit the process. Is never  ok to do that for an issue with a dowsntream connection.

**Comment by plebhash** [comment]
ok I'm trying to understand what needs to be done here. 

```
        PoolError::RolesLogic(_) => {
            send_status(sender, e, error_handling::ErrorBranch::Break).await
        }
```
my understanding is that we want to expand this case into multiple potential failure cases coming from roles logic.
we should call `send_status` with `error_handling::ErrorBranch::Break` only when there's no downstream attack vector (forcing an error to shut down the pool).

is that a correct understanding?
if so, where can I find a list of all possible failure cases?

---

with regards to the [second link](https://github.com/stratum-mining/stratum/blob/main/roles/pool/src/lib/mining_pool/mod.rs#L382), do we want to replace the `todo!` with a call to `handle_error`?

**Comment by Fi3** [comment]
Handling each possible case is a huge work. For now I would just fix the issue at hand.

**Comment by plebhash** [comment]
> Handling each possible case is a huge work. For now I would just fix the issue at hand.

I agree, but it might be a good idea to have an issue to keep track of this effort.

Maybe it doesn't have to be this issue and we can keep the focus here on this pool downstream connection issue, but maybe we should create a new issue to keep track of this effort from a high level?

cc @pavlenex

**Comment by pavlenex** [comment]
I think it makes sense to keep a scope, we can have a larger issue tracker (new one) where we can reference to all places where we need to fix this. If you can - feel free to log it @plebhash 🙏

**Comment by plebhash** [comment]
> I think it makes sense to keep a scope, we can have a larger issue tracker (new one) where we can reference to all places where we need to fix this. If you can - feel free to log it @plebhash 🙏

I created 2 new issues:
- #777 as a generic version of #773
- #778 as as a catch-all issue, which also references #736 (which goes in a similar direction, so it makes sense to aggregate)
