### ISSUE TITLE
small bugs in the JDS mempool

### ISSUE THREAD

**Issue by lorbax** [stratum-mining/stratum#784]
Here
[https://github.com/stratum-mining/stratum/blob/main/roles/jd-server/src/lib/mempool/mod.rs#L85](https://github.com/stratum-mining/stratum/blob/main/roles/jd-server/src/lib/mempool/mod.rs#L85)
there is a tokio task that is awaited, which does not make any sense. Since the function `update_mempool` is already an async method, I think that the generation of a new task can be definitely can be avoided without any substantial work.

Also the rpc method `get_raw_mempool_verbose` should be renamed with `get_raw_mempool`, as at the end the rpc call is `getrawmempool` without verbose.

good for first issue!

**Comment by NonsoAmadi10** [comment]
Hi @pavlenex i would love to take a go at this task, can I?

**Comment by pavlenex** [comment]
Go for it!

**Comment by 0xSaksham** [comment]
@pavlenex is this still open?

**Comment by NonsoAmadi10** [comment]
@0xSaksham I opened a PR for it. It is still in review

**Comment by pavlenex** [comment]
Completed in #833
