### ISSUE TITLE
Create / fix / document sv2 CPU miner

### ISSUE THREAD

**Issue by Sjors** [stratum-mining/stratum#798]
One thing I noticed during my Stratum v2 workshop in London is that's it really hard to test things without a CPU miner.

Right now you have to get a CPU miner from somewhere else, e.g. https://github.com/pooler/cpuminer/ which may or may not compile. And then you have to build and configure the translator role.

There's a [mining-device](https://github.com/stratum-mining/stratum/tree/main/roles/test-utils/mining-device) under test-utils. I'm guessing this is a CPU miner? But it's undocumented and it's not clear what the status is.

In any case, it would be nice to have a simple CPU miner that can be pointed directly at an sv2 pool (and job declarator client??).

It does not have to be efficient; a custom signet can have very low difficulty.

**Comment by Fi3** [comment]
the mining-device in test-utils is an header only downstream, is used mostly for test but with few changes can be  eg parsing args to get upstream endpoint can be transformed in what you are looking for.

**Comment by Fi3** [comment]
it still use unencrypted connection so we need to change also that, if we agree on what we want from the cpu miner I can do PR improve it @Sjors

**Comment by Sjors** [comment]
What I'd like to do with it is to simply point the CPU miner to the pool role (or to the job declarator client) and then it should produce block.

Nice to have:
1. set a target `--nbits`, so that it mines only enough blocks to keep the difficulty at that level
2. check the (pool) certificcate

**Comment by plebhash** [comment]
@Fi3 I guess this issue is also related: https://github.com/stratum-mining/stratum/issues/607

**Comment by GitGab19** [comment]
@Fi3 did you know if issues #607, #529 have been addressed by your PR #819 that we merged last week?

**Comment by Sjors** [comment]
This works, so I'm going to close the issue. But I do have a followup: #850
