### ISSUE TITLE
add ARM architecture support on `release-bin.yaml`

### ISSUE THREAD

**Issue by plebhash** [stratum-mining/stratum#815]
Currently we only support the following platforms on the `Release Binaries` pipeline:
- `aarch64-apple-darwin`: MacOS Apple Silicon (M1+M2)
- `x86_64-apple-darwin`: MacOS x86-64
- `x86_64-linux-gnu`: Linux x86-64

As described in https://github.com/stratum-mining/stratum/pull/684, it is also desirable to support ARM SoCs and SBCs.
The two most popular architectures being:
- `aarch64-unknown-linux-gnu`
- `arm-unknown-linux-gnueabi`

I started working on this a while ago by proposing a shell script via PR #684, but since we have a binary release pipeline, it makes more sense add support for these targets via [`release-bin.yaml`](https://github.com/stratum-mining/stratum/blob/main/.github/workflows/release-bin.yaml) instead, without adding any additional shell script.

This could also be useful: https://github.com/houseabsolute/actions-rust-cross

It is a Github Action that allows cross-compilation of Rust projects via [cargo cross](https://github.com/cross-rs/cross).

While working on this issue, the contributor should make some mock releases on their fork as a way to validate that the workflow is behaving as expected.

**Comment by xyephy** [comment]
Hi @plebhash, is it okay if I give this a try?

**Comment by xyephy** [comment]
@plebhash  I've managed to do the releases : https://github.com/xyephy/stratum/releases/tag/dev.
working file: https://github.com/xyephy/stratum/blob/dev/.github/workflows/release-bin.yaml
Used [cargo cross](https://github.com/cross-rs/cross) as you had suggested.
Kindly check them out before I do a PR

**Comment by xyephy** [comment]
> > @plebhash I've managed to do the releases : https://github.com/xyephy/stratum/releases/tag/dev. working file: https://github.com/xyephy/stratum/blob/dev/.github/workflows/release-bin.yaml Used [cargo cross](https://github.com/cross-rs/cross) as you had suggested. Kindly check them out before I do a PR
> 
> LGM

I've pushed PR #864

**Comment by pavlenex** [comment]
Closed in #864
