### ISSUE TITLE
config parameters not used for anything

### ISSUE THREAD

**Issue by plebhash** [stratum-mining/stratum#818]
some example config files have a fields that are never really used for anything in the roles implementations

- `coinbase_reward_sat`

the config files should be cleaned up from those values

**Comment by star-gazer111** [comment]
So the task as I understand is simply about commenting or removing those parameters from the example config files right @plebhash ?

**Comment by plebhash** [comment]
yes, but removing is better... leaving them as comments is just as useless as they are now

and the list above is just examples, I didn't look in detail through all the roles

ideally one should make a deep inspection trying to find all instances of unused config parameters 

it can be done with a `grep` command, for example

**Comment by star-gazer111** [comment]
inspected & fixed here #837

**Comment by star-gazer111** [comment]
I suppose this can be closed now @plebhash

**Comment by plebhash** [comment]
closed via https://github.com/stratum-mining/stratum/pull/838

**Comment by saadbitcoin** [comment]
oky isee
