### ISSUE TITLE
Split JobDeclaratorDownstream of JD-Server and Downstream of Pool in a separate module

### ISSUE THREAD

**Issue by lorbax** [stratum-mining/stratum#824]
The [JobDeclaratorDownstream](https://github.com/stratum-mining/stratum/blob/dev/roles/jd-server/src/lib/job_declarator/mod.rs#L47) struct of JD-server and the [Downstream](https://github.com/stratum-mining/stratum/blob/dev/roles/pool/src/lib/mining_pool/mod.rs#L97) structs should be in a separate modules.
This should be take as a first step of @plebhash plan of making all the roles' code homogeneous.

Good for first issue!

**Comment by plebhash** [comment]
I'm submitting 2 PRs to close this issue:
- #832 
- #831

**Comment by pavlenex** [comment]
@plebhash Should this issue be closed considering #831 and #832 for now?
