### ISSUE TITLE
Add Mocked Job Negotiator and Mocked Template Provider Message to message-generator

### ISSUE THREAD

**Issue by Fi3** [stratum-mining/stratum#83]

**Comment by rrybarczyk** [comment]
Tests can be done without using mocks, but for integration tests to be complete, a mock JN and a mock TP should be made and used in another binary application to properly test the proxy.

**Comment by GitGab19** [comment]
I thing this can be closed since both JD and TP mock are present in MG mocks (https://github.com/stratum-mining/stratum/tree/main/test/message-generator/mock)
