### ISSUE TITLE
Test TP <-> (Proxy) JN <-> (Pool) JN

### ISSUE THREAD

**Issue by Fi3** [stratum-mining/stratum#84]

**Comment by rrybarczyk** [comment]
Check that when the Proxy JN recieves some messages, it responds with the appropriate way.
Consider:
- [ ] Mocking the TP and the Pool JN, to properly test the Proxy JN
- [ ] Mocking the TP and the Proxy JN, to properly test the Pool JN

**Comment by pavlenex** [comment]
This one was done in mvp2
