### ISSUE TITLE
Custom transactions from JDC removed from mempool during update

### ISSUE THREAD

**Issue by lorbax** [stratum-mining/stratum#840]
The declared transaction in declared mining job are stored as a whole in the JDS mempool. The transactions in in declared jobs are recognized because they have this form (like `txid: Txid <-- Some(Transaction)` in the hashmap). In `JDsMemppol::update_mempool()` we create a new hashmap `mempool_ordered`. Inside the task spawned, the node's mempool is stored in in the variable `mempool: Vec<Txid>`. For every entry `txid` of this vector, if there was a transaction in the mutex mempool of the form `txid: Txid <-- Some(Transaction)`, then the whole transaction is stored in `mempool_ordered`. The other transactions in `mempool` are stored in `mempool_ordered` as `txid: Txid <-- None`. Then JDS mempool is updated with `mempool_ordered`
[https://github.com/stratum-mining/stratum/pull/833](https://github.com/stratum-mining/stratum/pull/833)
As a consequence of that, if the downstream declares a transaction which is unknown to the node, then it gets lost during the update of the JDS mempool. If the mempool is updated frequently this may prevent to the block propagation for the JDS, which is not good.

If this is fixed, we must also remove the transactions of old declared jobs, otherwise the there is (very remote) risk of overflow.

Fix this issue after merging of [PR833.](https://github.com/stratum-mining/stratum/pull/833)

**Comment by NonsoAmadi10** [comment]
Alright @lorbax i will take this issue up. Let me make the requested changes on #833
