### ISSUE TITLE
JDC is not doing fallback to solo-mining

### ISSUE THREAD

**Issue by GitGab19** [stratum-mining/stratum#844]
During testing, I noticed that sometimes JDC disconnects from upstreams because of some shares refused by the pool (this needs to be investigated better).
In this case, our default config for JDC doesn't contain a second upstream, so JDC should fallback to solo-mining.
But it's not doing that, instead it just hangs there.

**Comment by GitGab19** [comment]
For a better context, here's a screenshot I did when I noticed the bug during testing:
![Uploading Screenshot 2024-04-08 at 15.24.09.png…]()

**Comment by GitGab19** [comment]
To reproduce the issue, just try to fake the prev_hash used by the pool to check shares sent by downstream, by changing line 1159 in [protocols/v2/roles-logic-sv2/src/channel-logic/channel_factory.rs](https://github.com/stratum-mining/stratum/blob/24b8b1d8666d6055c4a964d2aac8ef2445734a10/protocols/v2/roles-logic-sv2/src/channel_logic/channel_factory.rs#L1159) with this:

//let prev_blockhash = crate::utils::u256_to_block_hash(referenced_job.prev_hash.clone());
let prev_blockhash = crate::utils::u256_to_block_hash([220, 157, 233, 68, 198, 232, 73, 141, 133, 12, 97, 197, 97, 244, 132, 146, 127, 171, 248, 91, 23, 159, 215, 209, 2, 0, 0, 0, 0, 0, 0, 0].into());

**Comment by plebhash** [comment]
> To reproduce the issue, just try to fake the prev_hash used by the pool to check shares sent by downstream, by changing line 1159 in [protocols/v2/roles-logic-sv2/src/channel-logic/channel_factory.rs](https://github.com/stratum-mining/stratum/blob/24b8b1d8666d6055c4a964d2aac8ef2445734a10/protocols/v2/roles-logic-sv2/src/channel_logic/channel_factory.rs#L1159) with this:
> 
> //let prev_blockhash = crate::utils::u256_to_block_hash(referenced_job.prev_hash.clone()); let prev_blockhash = crate::utils::u256_to_block_hash([220, 157, 233, 68,

it would be good to reproduce this with MG

**Comment by plebhash** [comment]
partially solved by https://github.com/stratum-mining/stratum/issues/1004
