### ISSUE TITLE
JDC is not logging any error on wrong TP configuration

### ISSUE THREAD

**Issue by GitGab19** [stratum-mining/stratum#863]
JDC is not generating errors when a wrong TP configuration is used.
To reproduce it, you can simply change the port number randomly in `tp_address` parameter, and run it.
A discussion about this here: https://discord.com/channels/950687892169195530/1012371967992672321/1229368703737663508

**Comment by GitGab19** [comment]
I would label this as a `good-first-issue`.
Maybe I don't remember correctly, but didn't we do something in the past to fix these type of behaviours @plebhash ?

**Comment by plebhash** [comment]
> didn't we do something in the past to fix these type of behaviours?

can you be more specific? are you referring to wrong TP config, or `authority_public_key` vs `authority_pubkey`?

**Comment by GitGab19** [comment]
> > didn't we do something in the past to fix these type of behaviours?
> 
> can you be more specific? are you referring to wrong TP config, or `authority_public_key` vs `authority_pubkey`?

I don't remember specific details tbh. I just remember that we did something to better handle configurations in general, but maybe I'm wrong

**Comment by plebhash** [comment]
we had this issue: https://github.com/stratum-mining/stratum/issues/695
which was closed via https://github.com/stratum-mining/stratum/pull/859

**Comment by GitGab19** [comment]
> Happy to pick this up
> 
> @GitGab19 From what I understand from the discord discussion the user used `18442` instead of `8442` in one of the configs, but that is not strictly prohibited right? I wonder if this requires validation across configs or we should just validate its `8442` across all of configs?

Hey I'm sorry for being late.
So, imo the important thing is to validate the config in order to avoid cases like the one described here: https://github.com/stratum-mining/stratum/issues/863#issuecomment-2084696301.
The 8442 port is not strictly mandatory, a user could change it in both TP and roles config, so I would not require it to be always 8442

**Comment by Sjors** [comment]
Indeed, you could check that the port is a valid integer between 0 and 65535. But just checking that it's an integer should be enough.

**Comment by jbesraa** [comment]
Because we are using `serde` the `ser` and `de` errors are generated also by `serde` which is fine. so I didnt need to do much beside handling this error https://github.com/stratum-mining/stratum/pull/987/files#diff-49408d7d429f7afceda135baa9cdd786c20024ec6ffd2a05353efe1b0c5c2e75R110

**Comment by rrybarczyk** [comment]
See my comment [here](https://github.com/stratum-mining/stratum/pull/987#issuecomment-2185280150).

I think we should address just the JDC config issue as a patch if you think it is urgent, or wait until #997 which I just opened.

**Comment by GitGab19** [comment]
> See my comment [here](https://github.com/stratum-mining/stratum/pull/987#issuecomment-2185280150).
> 
> I think we should address just the JDC config issue as a patch if you think it is urgent, or wait until #997 which I just opened.

I would lean towards aggregating them into #997, since it seems a better wrapper for it. But @jbesraa feel free to let us know what you think about it (for me it's also ok to merge your contribution now)

**Comment by GitGab19** [comment]
Closed by #987
