### ISSUE TITLE
Deprecation notice: actions/checkout@v3, actions/upload-artifact@v3

### ISSUE THREAD

**Issue by xyephy** [stratum-mining/stratum#865]
Node.js 12 & 16 need upgrading to Node.js 20 in the GitHub workflow as shown in the screenshot below:
<img width="1030" alt="Screenshot " src="https://github.com/stratum-mining/stratum/assets/15778219/70243975-9be7-4b99-b126-a700ca8582ea">

**Comment by xyephy** [comment]
@plebhash any views on this?
should I work on the Node.js upgrade?

**Comment by plebhash** [comment]
> @plebhash any views on this? should I work on the Node.js upgrade?

sounds like a good improvement! 👍

**Comment by plebhash** [comment]
closed via #879
