### ISSUE TITLE
Dev branch is not on top of Main branch

### ISSUE THREAD

**Issue by lorbax** [stratum-mining/stratum#870]
Seems that dev branch is not on top of main. This is bad because if someone wants contribute and fork the project from main, we must ask them to rewrite their PRs.
The most recent commit that both dev and main share is [this one](https://github.com/stratum-mining/stratum/commit/7c96c4ecf48c490aa0494aca328f7ae2dfce233c).

**Comment by Fi3** [comment]
this is bad cause when we want to merge dev on main wont be automatic. If someone fork from main he will always need to rebase on dev and it just shouldn't create the new branch from main

**Comment by plebhash** [comment]
I created #871 merging `main` into `dev`, which should make the branches back to sync again

**Comment by plebhash** [comment]
closed via https://github.com/stratum-mining/stratum/pull/871 +  https://github.com/stratum-mining/stratum/pull/872
