### ISSUE TITLE
undeterministic connection between JDC and pool

### ISSUE THREAD

**Issue by plebhash** [stratum-mining/stratum#874]
## context

[we had a community member reporting they could not connect a JDC to our hosted setup (TP + pool + JDS)](https://discord.com/channels/950687892169195530/950687892169195533/1234126304102580285)

I logged into the VPS and noticed the pool was frozen. 
The reason why the pool was frozen is unknown, but outside the scope of this issue.

This issue is an initial report of some bug on JDC + Pool. The root cause is still unknown, and requires more investigation.

### test 1

After restarting pool + JDS processes on the VPS, I was able to connect JDC + tProxy, but tProxy crashed as soon as I started CPU miner

### test 2

I restarted JDC + tProxy on my machine, but when I tried to restart JDC, it would consistently get its connection rejected by the pool.

JDC logs:
![image](https://github.com/stratum-mining/stratum/assets/147345153/b4b374a3-a293-4266-94df-605a8d3ff70e)

pool logs:
![image](https://github.com/stratum-mining/stratum/assets/147345153/a5fee756-72c0-41bd-befd-8738c71e77e6)

### test 3

restarted pool + JDS on VPS, attempted to reconnect JDC, to see the same behavior.

I kept trying to reconnect JDC (without restarting pool + JDS), the behavior kept repeating.
until eventually I saw some different behavior: immediately after some errors I got a successful connection

pool logs were identical to test 2 (followed by normal logs)

JDC logs:
![image](https://github.com/stratum-mining/stratum/assets/147345153/345eb545-7cf4-4652-b2ac-311feca28ed1)

### test 4

killed JDC, started again... different error messages, unsuccessful connection.

pool logs were identical to test 2 (followed by normal logs)

JDC logs:
![image](https://github.com/stratum-mining/stratum/assets/147345153/bcba3f8a-32e2-40bb-ae96-0721000714c2)

### test 5

killed JDC, started again... different error messages, unsuccessful connection.

pool logs were identical to test 2 (followed by normal logs)

JDC logs:
![image](https://github.com/stratum-mining/stratum/assets/147345153/9b5d560b-0bda-44c8-9632-0047b2164432)

### test 6

killed JDC, started again... different error messages, but now, successful connection.

pool logs were identical test 2 (followed by normal logs)
JDC logs were identical to test 3

**Comment by Fi3** [comment]
this is most likely due to issue with the certificate validity time

**Comment by plebhash** [comment]
> this is most likely due to issue with the certificate validity time

@Fi3 do you have any suggestions for next steps in testing, and potentially fixing this issue?

**Comment by Fi3** [comment]
Not really, I would start playing with this function https://github.com/stratum-mining/stratum/blob/main/protocols/v2/noise-sv2/src/signature_message.rs#L27

**Comment by pavlenex** [comment]
Is this still relevant?
