### ISSUE TITLE
tproxy: `HexError(OddLength)` in `mining.subscribe`

### ISSUE THREAD

**Issue by plebhash** [stratum-mining/stratum#896]
recently we had PR https://github.com/stratum-mining/stratum/pull/851 by @nikicat

I noticed we didn't have an issue here on github to track this (potential) bug

**Comment by plebhash** [comment]
also, it took me some time to figure out how to reproduce this bug deterministically.

this issue is a good place to register my findings

here are instructions to reproduce the bug:

1. start tProxy
2. start netcat: `nc localhost 34255`
3. send a `mining.subscribe` with an extranonce of even length (this should work fine): `{"id": 1, "method": "mining.subscribe", "params": ["", "00"]}`
4. start netcat again: `nc localhost 34255`
5. send a `mining.subscribe` with an extranonce of off length (this should trigger the bug on tProxy): `{"id": 1, "method": "mining.subscribe", "params": ["", "0"]}`

**Comment by plebhash** [comment]
I'm also backtracing the bug to find the root cause:

inside `pub async fn new_downstream` we have a call to `handle_incoming_sv1 `:

https://github.com/stratum-mining/stratum/blob/24b8b1d8666d6055c4a964d2aac8ef2445734a10/roles/translator/src/lib/downstream_sv1/downstream.rs#L180

which calls `handle_message`:

https://github.com/stratum-mining/stratum/blob/24b8b1d8666d6055c4a964d2aac8ef2445734a10/roles/translator/src/lib/downstream_sv1/downstream.rs#L375-L381

which calls `handle_request`:

https://github.com/stratum-mining/stratum/blob/24b8b1d8666d6055c4a964d2aac8ef2445734a10/protocols/v1/src/lib.rs#L77

the issue seems to be in the `try_into()?`, which is implemented at:

https://github.com/stratum-mining/stratum/blob/24b8b1d8666d6055c4a964d2aac8ef2445734a10/protocols/v1/src/methods/mod.rs#L142-L146
 
the nested `try_into()?` (line 146 above) is implemented at:
https://github.com/stratum-mining/stratum/blob/24b8b1d8666d6055c4a964d2aac8ef2445734a10/protocols/v1/src/methods/mod.rs#L214-L229

the nested `try_into()?` (line 226 above) is implemented at:
https://github.com/stratum-mining/stratum/blob/24b8b1d8666d6055c4a964d2aac8ef2445734a10/protocols/v1/src/methods/client_to_server.rs#L313-L342

**Comment by plebhash** [comment]
after going through the backtrace above, it seems the root cause of the issue is:
https://github.com/stratum-mining/stratum/blob/24b8b1d8666d6055c4a964d2aac8ef2445734a10/protocols/v1/src/methods/client_to_server.rs#L323-L324

it is calling `hex::decode` `extranonce1` field that was sent as the second parameter of the JSON-RPC message (`JString(b)`).

if there's an odd number of characters, `hex::decode` returns an error, [as expected](https://docs.rs/hex/latest/hex/fn.decode.html).

so the question here is:

is it safe to assume `extranonce1` will always be encoded as hex?
because if that is a safe assumption, there is no bug here.

**Comment by plebhash** [comment]
hey @nikicat I just re-read your comment here:
https://github.com/stratum-mining/stratum/pull/851#issuecomment-2063719329

> it was just a coincidence that a miner with an odd-sized extranonce stopped subscribing.

So you saw this with real miners? Tying back to the question I asked on my comment above:
> on mining.subscribe message, is extranonce1 always encoded as hex bytes?

Or in other words, does this situation (extranonce with odd characters) ever really happens in real life, or did you manually generate this `mining.subscribe` message?

**Comment by plebhash** [comment]
again on my question on the above comments:
> on `mining.subscribe` message, is  `extranonce1` always encoded as hex bytes in the JSON-RPC?

![image](https://github.com/stratum-mining/stratum/assets/147345153/cb8d396c-c8e3-4f6d-8a93-13614f063922)
ref: https://en.bitcoin.it/wiki/Stratum_mining_protocol#mining.subscribe

if the `extranonce1` value is hex encoded in the result response, that is a pretty good indication that it is also hex encoded in the request

**Comment by plebhash** [comment]
@nikicat confirmed to me that this behavior was generated from a real machine. It is probably running crazy firmware that is not compliant with SV1 spec.

Nevertheless, the contribution on #851 makes sense, since it wouldn't be wise to block SRI adoption due to technical purism.
so we can just allow for odd-length `extranonce1` values on tProxy.

**Comment by plebhash** [comment]
closed via #851

**Comment by Fi3** [comment]
Not sure that we should accept odd len string. 1 byte is always 2 char so how is possible to have an odd len string? You assume a leading 0 that is not in the string, where is the 0?

 I would rather close the connection since invalid coinbase means invalid block. (for example when the extranonce end up being 1 byte shorter or longer). If we are 100% that this can not happen, and we want to accept odd len string, we should document why is ok to accept odd len string.

**Comment by plebhash** [comment]
> Not sure that we should accept odd len string. 1 byte is always 2 char so how is possible to have an odd len string? You assume a leading 0 that is not in the string, where is the 0?
> 
> I would rather close the connection since invalid coinbase means invalid block. (for example when the extranonce end up being 1 byte shorter or longer). If we are 100% that this can not happen, and we want to accept odd len string, we should document why is ok to accept odd len string.

I think one way to be 100% sure is to reproduce this scenario via MG and check if it results on an invalid block.
From that we have two courses of action:
- Invalid block happens: we revert [PR #851](https://github.com/stratum-mining/stratum/pull/851) before `dev` branch is merged into `main`
- No invalid block happens: we add a new PR documenting why this is accepted behavior on tProxy.

@Fi3 would you agree with this approach?

**Comment by Fi3** [comment]
yep make sense

**Comment by plebhash** [comment]
> > Not sure that we should accept odd len string. 1 byte is always 2 char so how is possible to have an odd len string? You assume a leading 0 that is not in the string, where is the 0?
> > I would rather close the connection since invalid coinbase means invalid block. (for example when the extranonce end up being 1 byte shorter or longer). If we are 100% that this can not happen, and we want to accept odd len string, we should document why is ok to accept odd len string.
> 
> I think one way to be 100% sure is to reproduce this scenario via MG and check if it results on an invalid block. From that we have two courses of action:
> 
> * Invalid block happens: we revert [PR #851](https://github.com/stratum-mining/stratum/pull/851) before `dev` branch is merged into `main`
> * No invalid block happens: we add a new PR documenting why this is accepted behavior on tProxy.
> 
> @Fi3 would you agree with this approach?

ok I changed my mind... even though I'm 100% in favor of writing as many MG tests as possible, I don't think it's worth the effort on this issue.

From my research listed above, this is an impossible situation on a protocol level, and @Fi3 seems to be in agreement with this.

Even if this happens on real ASICs, it's a fault on firmware side that could potentially end up in invalid blocks, so I agree it should be rejected.

I propose we revert #851 via #952 and finally close this issue.

**Comment by plebhash** [comment]
@nikicat we appreciate your contribution

if you still want to help SRI, I have a suggestion on this comment: https://github.com/stratum-mining/stratum/issues/896#issuecomment-2094345538

**Comment by plebhash** [comment]
closed via https://github.com/stratum-mining/stratum/pull/952

**Comment by nikicat** [comment]
Hello, it's a little frustrating that fixing this bug took less time than the discussion about whether the fix should be accepted.
A bit of the story: I'm developing a Bitcoin <-> EVM bridge (one more, yeah) and need liquidity to test it on a testnet. I've struggled to find a reliable faucet for testnet3 so I tried to mine it using rented miners (from https://www.miningrigrentals.com/). To my confusion, the [p2pool](https://github.com/jtoomim/p2pool/) was abandoned many years ago, but luckily I found this project so I can solve my issue. I've set up a local cluster with pool, jds, jdc, and tproxy, made tproxy port available for external miners, and rented a couple of rigs from https://www.miningrigrentals.com/ hoping that I buy this way enough tBTC for my development. But pretty soon the `HexError(OddLength)` started to show in logs and ruin the miners' performance (yes, not all miners send truncated hex strings, but a significant part of them). I've looked through the Stratum codebase and pretty quickly found that it uses two different methods for parsing hex strings in received messages: using plain `hex::decode` and using (hex_decode)[https://github.com/nikicat/stratum/blob/dev/protocols/v1/src/utils.rs#L43-L51] from `protocols/v1/src/utils.rs` that patches odd-sized hex strings. I've come to the pretty obvious (at least for me) conclusion that it's just a little bug that this function is not used in all the cases, so I patched the code and my pool started to fully utilize rented miners. After that, I opened #851 PR to share my fix with others who will work with similarly behaving miners too. Afterward, I added some tests when @GitGab19 asked me to do so.
That's mostly the story, and I want to conclude:
 - There is no clear standard on the stratum v1 protocol AFAIK
 - I prefer to follow (Robustness principle)[https://en.wikipedia.org/wiki/Robustness_principle] when I develop network services
 - There could be (and there actually are - i.e. I have another similar non-compliant fix) other "violations" of the stratum v1 protocol by hardware miners

So, if you are not willing to accept such changes, what in your opinion is a "true fix" for my or similar cases? As you understand, I can't force miner owners to somehow "fix" their miners (I suppose they can't even if they wanted to). Should it be a (separate from Stratum) translation proxy that fixes "broken" stratum v1 messages? Or should it be just a more permissive fork of Stratum (this is my actual solution)? I just want to know your policy and plans so I can better allocate my time on this project.

**Comment by plebhash** [comment]
> So, if you are not willing to accept such changes, what in your opinion is a "true fix" for my or similar cases? As you understand, I can't force miner owners to somehow "fix" their miners (I suppose they can't even if they wanted to). Should it be a (separate from Stratum) translation proxy that fixes "broken" stratum v1 messages? Or should it be just a more permissive fork of Stratum (this is my actual solution)? I just want to know your policy and plans so I can better allocate my time on this project.

I have a suggestion on this comment: https://github.com/stratum-mining/stratum/issues/896#issuecomment-2094345538

I understand your frustration, but from an objectively technical standpoint, a Proxy that allows for shares on invalid blocks is not a sane implementation of the protocol

economically speaking, the fact that there is faulty SV1 firmware in the wild is a market inefficiency, and you should re-evaluate on whether miningrigrentals.com is meeting your business needs. My advice is that you give them this feedback and look for alternatives.

**Comment by nikicat** [comment]
> from an objectively technical standpoint, a Proxy that allows for shares on invalid blocks is not a sane implementation of the protocol
As far as I can tell all produced blocks are valid with my this patch.

> economically speaking, the fact that there is faulty SV1 firmware in the wild is a market inefficiency, and you should re-evaluate on whether miningrigrentals.com is meeting your business needs. My advice is that you give them this feedback and look for alternatives.
From my point of view, they work fine - I've got a bunch of testnet3 (and later testnet4) BTC for a reasonable price of several bucks.

**Comment by nikicat** [comment]
> > hoping that I buy this way enough tBTC
> 
> if that is all you want, just drop a [ckpool-solo](https://bitbucket.org/ckolivas/ckpool-solo/downloads/). It's been around for ages and I already mined a bunch of `testnet4` tBTC with it (however no rentals, just some ASIC I have locally).

I'll look through it, thanks. But, taking into account that it's written in C and the time I've spent with the Stratum codebase, I think it's currently easier for me to continue working with Stratum.

**Comment by Fi3** [comment]
My main issue with that is that is not clear how you should reconstruct a byte array from an odd len hex string. There are several ways in which you can transform the hex string in a byte array and no one is more correct than the other. I am wrong here? If yes could make sense to accept the PR, if not the Robustness principle do not stand here as the meaning of the message is not clear at all. @nikicat

**Comment by nikicat** [comment]
> @nikicat are you sure that this is an issue with the actual miner firmware and not with https://www.miningrigrentals.com/ ?

www.miningrigrentals.com proxies all the stratum-v1 traffic through itself and I don't know if it reencodes requests/responses or passes them unchanged as a text. I could try to check the next time I will mine if there are any extranonces with leading zeros - if yes, then it depends on a miner, if no for several miners - then it's probably a miningrigrentals.com issue (quite understandable though if they use Python on a backend).

**Comment by Fi3** [comment]
IMO interpreting it as an int is not more correct than interpreting it as a byte array and encode each u8 without the leading 0. If you interpret it as an int you don't even know the endianness for example. I don't want to be pedant here, is just that I'm not sure that adapting the code to support a bugged implementation instead of another possible bugged implementation make too much sense. What if tomorrow we discover another service that broke the impl in an way that is incompatible with this patch? We should support the other impl or miningrentals?

**Comment by nikicat** [comment]
I've checked the old logs and it seems like miningrigrentals.com isn't involved in producing odd-sized extranonces. Moreover, there are odd-sized nonces with leading zeros:

```
000021de1
0000508d1
0000704d1
000084b61
0000bafb1
018bba311
01a7fb6a1
01fcc0451
021902031
0243649c1
028a09001
02d0ad6c1
1de87b021
21e10a021
291cb6011
2fefec021
3ac76d021
4ecede021
59a65f021
778551021
79ce00001
a66bb4021
a9997d011
ae6812eb4cd7735a302a8a9dd95cf71f
b47100001
bd5dd2011
d4da99011
e02227021
e32998021
f4a303c7f21e0fd4
```

**Comment by Fi3** [comment]
this is odd :rofl:

**Comment by Fi3** [comment]
fair but my main point is that extranonce is not an int and for that interpreting it such an int is fundamentally wrong

**Comment by nikicat** [comment]
@Fi3 what do you think about ignoring the "incorrect" extranonce1 parameter, i.e. as if there are no extranonce1? I suppose this should not break anything and https://www.miningrigrentals.com/ miners will work fine.

**Comment by Fi3** [comment]
Maybe I'm misunderstood something, or maybe there is a typo, but we are talking about extranonce2 right? If not why downstream is sending an extranonce1? Is that for restore an old session? If this is the case I assume we can add a field or something were we say we we want to support session restoring and if not we can just ignore the incorrect extranonce1 parameter (it is incorrect cause can not be an odd string)

**Comment by nikicat** [comment]
I think from the beginning it was a PR and issue about mining.subscribe and extranonce1 consequentially. And yes, this is about the session restoring, we can safely ignore it, and I'm not sure if we even need a config parameter for it - if extranonce1 is valid and we have a corresponding session - then use it, if not - just ignore it.

**Comment by Fi3** [comment]
make sense if we are going to send a new extranonce1 we don't care about the old one
