### ISSUE TITLE
JDC executes fallback system too frequently

### ISSUE THREAD

**Issue by GitGab19** [stratum-mining/stratum#901]
While digging into issue #844, I discovered that JDC enters in the fallback mechanism too frequently.
I discovered the reason for that, and it's related to the `prev_hash` contained in shares. 
- Sometime (I still don't know exactly why) a valid share is sent to the pool (in this case through JDC) with the correct `prev_hash`.
- When the valid share is checked by the pool, the pool uses a wrong `prev_hash` in the `check_target` function, and so the share is not a valid one for the pool.
- Pool sends a `SubmitShareError` message to JDC 
- JDC thinks that Pool is wrongly refusing the valid share and pool-fallback is started

JDC logs:
<img width="2560" alt="Screenshot 2024-05-08 at 18 25 43" src="https://github.com/stratum-mining/stratum/assets/62447440/82ca3f97-14fd-46b5-9489-6c56605f0346">

Pool logs:
<img width="2560" alt="Screenshot 2024-05-08 at 18 26 48" src="https://github.com/stratum-mining/stratum/assets/62447440/5028beaa-b3db-4a3c-b7a2-3eae7d030922">

**Comment by pavlenex** [comment]
Done in #904
