### ISSUE TITLE
regtest configurations

### ISSUE THREAD

**Issue by rockcoolsaint** [stratum-mining/stratum#906]
It will be highly desirable to have special configuration files for regtest

A good example is the file below

https://github.com/stratum-mining/stratum/blob/dev/roles/translator/config-examples/tproxy-config-local-pool-example.toml

Where values like: `min_individual_miner_hashrate=10_000_000_000_000.0` can be pre-configured for regtest/development purpose
e.g:

```
# hashes/s of the weakest miner that will be connecting (e.g.: 10 Th/s = 10_000_000_000_000.0)
min_individual_miner_hashrate=10_000_000.0 # modified for local development
...
# estimated accumulated hashrate of all downstream miners (e.g.: 10 Th/s = 10_000_000_000_000.0)
channel_nominal_hashrate = 10_000_000.0 # modified for local development
```

**Comment by pavlenex** [comment]
@plebhash @GitGab19 thoughts?

I am a bit worried we may be overcomplicating things with too many configs for people to try. Didn't we have something similar in the past?

**Comment by GitGab19** [comment]
@rockcoolsaint I don't think that adding a new config just for the purpose of changing those 2 values has some real value.
