### ISSUE TITLE
jdc-config-hosted-example.toml connection error

### ISSUE THREAD

**Issue by daquexian** [stratum-mining/stratum#907]
When I run `cargo run -- -c jdc-config-hosted-example.toml` (https://stratumprotocol.org/getting-started/#run-job-declarator-client-jdc), I got this error:

```
ERROR jd_client::lib::upstream_sv2::upstream: Failed to connect to Upstream role at 75.119.150.111:34254, retrying in 5s: Connection refused (os error 61)
```

`telnet` shows a similar error, too:

```
$ telnet 75.119.150.111 34254
Trying 75.119.150.111...
telnet: connect to address 75.119.150.111: Connection refused
telnet: Unable to connect to remote host
```

**Comment by pavlenex** [comment]
@GitGab19 can you check this report please when you get a chance? What's the most common problem when this error happens, do you remember?

**Comment by GitGab19** [comment]
> @GitGab19 can you check this report please when you get a chance? What's the most common problem when this error happens, do you remember?

For some reason our infrastructure was stuck. I just restarted everything.
@daquexian can you try now?

**Comment by daquexian** [comment]
> ping @daquexian ^ 🙏

Thanks for your great work! It now works.  @pavlenex @GitGab19
