### ISSUE TITLE
make sure `Error` types from `protocols` crates implement `std::error::Error`

### ISSUE THREAD

**Issue by plebhash** [stratum-mining/stratum#921]
an idea to improve error handling on the roles implementation is to start using the `anyhow` crate https://github.com/stratum-mining/stratum/issues/736#issuecomment-2123412432

as a prerequisite, all custom `Error` types from the low-level crates under `protocols` must implement the `std::error::Error` trait

**Comment by rockcoolsaint** [comment]
This then means that you're handling this issue right?

**Comment by plebhash** [comment]
> This then means that you're handling this issue right?

hey! this is actually on my backlog, if you wanna give it a go, feel free!

my suggestion would be:
- branch off from `feat-optional-no-std` on my fork, to make sure that we can merge your PR after [#932](#932) is merged
- do what I'm describing on the description of this issue, as well as the comment below it
- send a draft PR

once you submit your PR, I'll make sure to add to the description of [#932](#932) that we should merge yours afterwards

**Comment by rockcoolsaint** [comment]
Alright

**Comment by rockcoolsaint** [comment]
@plebhash should the 'anyhow' crate be applied to every instance of `unwrap()` or strictly functions that return `Result<>` type?
Moreover, there are way too many instances where `unwrap()` is used in roles crate alone. Will refactoring everyone of those instances be appropriate?

**Comment by plebhash** [comment]
this issue is only related to making sure `Error` types from `protocols` crates implement `std::error::Error`

while the potential introduction of `anyhow` is the motivation, it is not the focus here... that is future discussion.

**Comment by plebhash** [comment]
@rockcoolsaint thanks for your effort on this one

we decided to go on a different direction (https://github.com/stratum-mining/stratum/pull/932#pullrequestreview-2112344059), apologies if you spent a lot of effort on this one already

**Comment by rockcoolsaint** [comment]
Alright then, I'll pickup another issue
