### ISSUE TITLE
MG DSL

### ISSUE THREAD

**Issue by plebhash** [stratum-mining/stratum#943]
keeping in mind that every bug originated from Message ordering should be fixed via MG,

as a strategy to lower the barrier for contribution, we should add a module to `utils/message-generator` that parses some DSL

**Comment by pavlenex** [comment]
I've talked to @lorbax and this is something that we're moving to backlog for now, no particular time-frame as we're focused on MG test coverage in the next few releases.

**Comment by pavlenex** [comment]
Should we close this one considering #1077 ?
