### ISSUE TITLE
MG test templates

### ISSUE THREAD

**Issue by plebhash** [stratum-mining/stratum#953]
we have multiple MG tests available, however most of them are highly customized

whenever someone starts writing a MG test, they need to copy some pre-existing MG test and remove the unwanted features, which is a troublesome and error-prone activity

this doesn't scale well and is a massive bottleneck in bugfixing, especially considering the high verbosity inherent to JSON

we need a suite of templates for MG tests and mocks centered around each role, as well as common generic cases

**Comment by plebhash** [comment]
here's a suggestion for a layout:
```
test/message-generator
│└ test-templates
│   ├jdc-test-template.json
│   ├jds-test-template.json
│   ├pool-test-template.json
│   ├proxy-test-template.json
│   └translation-proxy-test-template.json
└─mock-templates
      ├jdc-mock-template.json
      ├jds-mock-template.json
      ├pool-mock-template.json
      ├proxy-mock-template.json
      └translation-proxy-mock-template.json
```

here we are adding two new directories to `test/message-generator`:
- `test-templates`: containing one `.json` file for each test template
- `mock-templates`: containing one `.json` file for each mock template

**Comment by GitGab19** [comment]
I think we should close this one, what do you think @plebhash ?
