### ISSUE TITLE
implement SV1 upstream logic for Message Generator

### ISSUE THREAD

**Issue by plebhash** [stratum-mining/stratum#971]
Message Generator is currently unable to behave as an SV1 Upstream

we need a new `setup_as_sv1_upstream` function on [`utils/message-generator/src/net.rs`](https://github.com/stratum-mining/stratum/blob/main/utils/message-generator/src/net.rs)

and then we need a new `match` arm here:

https://github.com/stratum-mining/stratum/blob/7841021e3f20280c62af119de5de58f421c6e428/utils/message-generator/src/executor_sv1.rs#L57-L71

**Comment by pavlenex** [comment]
Should this be closed or added to #1077 ?
